/*
 * Charts API
 *
 * An API for creating, retrieving, updating, and deleting charts
 *
 * API version: 2.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package chart

// A set of options that control the general appearance and operation of the chart.<br> **Note** Available for *all* values of `options.type` except for `Text`.
type GeneralOptions struct {
	// Determines if the chart displays samples from the data or plots every datapoint. By default, SignalFx uses sampling to provide better performance for charts.<br> **Note** Available for *all* values of `options.type` except for `Text`.
	DisableSampling bool `json:"disableSampling,omitempty"`
	// Time in milliseconds to wait before charting the available data and ignoring points that arrive afterwards. By default, SignalFx automatically detects and applies a sensible value. You can also choose the automatic option by explicitly setting `maxDelay` to 0. The maximum value is 900,000 ms (15 minutes).<br> **Note** Available for *all* values of `options.type` except for `Text`.
	MaxDelay int32 `json:"maxDelay,omitempty"`
	// The minimum resolution to use when computing the SignalFlow program, specified in milliseconds. By default, SignalFx computes and applies a sensible value. You can also choose the automatic option by explicitly setting `minimumResolution` to 0. The maximum value is 900,000 ms (15 minutes).<br> **Note** Available for *all* values of `options.type` except for `Text`.
	MinimumResolution int32 `json:"minimumResolution,omitempty"`
	// Specifies which time zone SignalFlow should use as the basis of calendar window transformation methods. For example, if you set `\"timezone\": \"Europe/Paris\"` and then use the transformation `sum(cycle=\"week\", cycle_start=\"Monday\")` in your chart's SignalFlow program, the calendar window starts on Monday, Paris time. <br> For a list of supported time zones, see [Timezones and SignalFlow calendar window transformations](https://developers.signalfx.com/charts_dashboards/charts_overview.html#_timezones_and_signalflow_calendar_window_transformations)
	Timezone string `json:"timezone,omitempty"`
}
