/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DashboardChartEventOverlay type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardChartEventOverlay{}

// DashboardChartEventOverlay Properties of an event overlay applied to each chart in a dashboard 
type DashboardChartEventOverlay struct {
	EventSignal DashboardEventSignal `json:"eventSignal"`
	// Event overlay ID. Set by system. 
	OverlayId *string `json:"overlayId,omitempty"`
	// List of filters to apply to events for this overlay 
	Sources []DashboardEventSources `json:"sources,omitempty"`
}

type _DashboardChartEventOverlay DashboardChartEventOverlay

// NewDashboardChartEventOverlay instantiates a new DashboardChartEventOverlay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardChartEventOverlay(eventSignal DashboardEventSignal) *DashboardChartEventOverlay {
	this := DashboardChartEventOverlay{}
	this.EventSignal = eventSignal
	return &this
}

// NewDashboardChartEventOverlayWithDefaults instantiates a new DashboardChartEventOverlay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardChartEventOverlayWithDefaults() *DashboardChartEventOverlay {
	this := DashboardChartEventOverlay{}
	return &this
}

// GetEventSignal returns the EventSignal field value
func (o *DashboardChartEventOverlay) GetEventSignal() DashboardEventSignal {
	if o == nil {
		var ret DashboardEventSignal
		return ret
	}

	return o.EventSignal
}

// GetEventSignalOk returns a tuple with the EventSignal field value
// and a boolean to check if the value has been set.
func (o *DashboardChartEventOverlay) GetEventSignalOk() (*DashboardEventSignal, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventSignal, true
}

// SetEventSignal sets field value
func (o *DashboardChartEventOverlay) SetEventSignal(v DashboardEventSignal) {
	o.EventSignal = v
}

// GetOverlayId returns the OverlayId field value if set, zero value otherwise.
func (o *DashboardChartEventOverlay) GetOverlayId() string {
	if o == nil || IsNil(o.OverlayId) {
		var ret string
		return ret
	}
	return *o.OverlayId
}

// GetOverlayIdOk returns a tuple with the OverlayId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardChartEventOverlay) GetOverlayIdOk() (*string, bool) {
	if o == nil || IsNil(o.OverlayId) {
		return nil, false
	}
	return o.OverlayId, true
}

// HasOverlayId returns a boolean if a field has been set.
func (o *DashboardChartEventOverlay) HasOverlayId() bool {
	if o != nil && !IsNil(o.OverlayId) {
		return true
	}

	return false
}

// SetOverlayId gets a reference to the given string and assigns it to the OverlayId field.
func (o *DashboardChartEventOverlay) SetOverlayId(v string) {
	o.OverlayId = &v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *DashboardChartEventOverlay) GetSources() []DashboardEventSources {
	if o == nil || IsNil(o.Sources) {
		var ret []DashboardEventSources
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardChartEventOverlay) GetSourcesOk() ([]DashboardEventSources, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *DashboardChartEventOverlay) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given []DashboardEventSources and assigns it to the Sources field.
func (o *DashboardChartEventOverlay) SetSources(v []DashboardEventSources) {
	o.Sources = v
}

func (o DashboardChartEventOverlay) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardChartEventOverlay) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["eventSignal"] = o.EventSignal
	if !IsNil(o.OverlayId) {
		toSerialize["overlayId"] = o.OverlayId
	}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	return toSerialize, nil
}

func (o *DashboardChartEventOverlay) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"eventSignal",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDashboardChartEventOverlay := _DashboardChartEventOverlay{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDashboardChartEventOverlay)

	if err != nil {
		return err
	}

	*o = DashboardChartEventOverlay(varDashboardChartEventOverlay)

	return err
}

type NullableDashboardChartEventOverlay struct {
	value *DashboardChartEventOverlay
	isSet bool
}

func (v NullableDashboardChartEventOverlay) Get() *DashboardChartEventOverlay {
	return v.value
}

func (v *NullableDashboardChartEventOverlay) Set(val *DashboardChartEventOverlay) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardChartEventOverlay) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardChartEventOverlay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardChartEventOverlay(val *DashboardChartEventOverlay) *NullableDashboardChartEventOverlay {
	return &NullableDashboardChartEventOverlay{value: val, isSet: true}
}

func (v NullableDashboardChartEventOverlay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardChartEventOverlay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


