/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChartOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChartOptions{}

// ChartOptions struct for ChartOptions
type ChartOptions struct {
	AreaChartOptions *PropertiesForAreaCharts `json:"areaChartOptions,omitempty"`
	// Controls appearance of markers for data arrival times 
	Axes []ChartAxes `json:"axes,omitempty"`
	// Precision of plot values 
	AxisPrecision *int32 `json:"axisPrecision,omitempty"`
	// Sets mechanism for coloring values 
	ColorBy *string `json:"colorBy,omitempty"`
	ColorRange *SpecifiesColorRangeOptionsForColoringAHeatmapChart `json:"colorRange,omitempty"`
	ColorScale *SpecifiesHowToApplyTheRangeOfSpecifiedColorValuesToDataInAHeatmapChart `json:"colorScale,omitempty"`
	// List of color range settings 
	ColorScale2 []ChartSecondaryVisualization `json:"colorScale2,omitempty"`
	// Default type for plots in this chart 
	DefaultPlotType *string `json:"defaultPlotType,omitempty"`
	// Chart properties 
	GroupBy []string `json:"groupBy,omitempty"`
	// Sorts groups of values in table charts 
	GroupBySort *string `json:"groupBySort,omitempty"`
	// Option to exclude missing metric values 
	HideMissingValues *bool `json:"hideMissingValues,omitempty"`
	HistogramChartOptions *ChartOptionsHistogramChartOptions `json:"histogramChartOptions,omitempty"`
	// Controls how 0 value affects Y-axis 
	IncludeZero *bool `json:"includeZero,omitempty"`
	LegendOptions *SetsTableOptions `json:"legendOptions,omitempty"`
	LineChartOptions *OptionsForALineChart `json:"lineChartOptions,omitempty"`
	// Text to display in a text chart 
	Markdown *string `json:"markdown,omitempty"`
	// Number of significant digits to use for data points in the chart 
	MaximumPrecision *int32 `json:"maximumPrecision,omitempty"`
	OnChartLegendOptions *DisplayOptionsForTheChartLegend `json:"onChartLegendOptions,omitempty"`
	ProgramOptions *GeneralOptionsForTheChart `json:"programOptions,omitempty"`
	// List of options for each plot in the chart 
	PublishLabelOptions []ChartPublishLabelOptions `json:"publishLabelOptions,omitempty"`
	// In milliseconds, refresh interval for chart 
	RefreshInterval *int32 `json:"refreshInterval,omitempty"`
	SecondaryVisualization *string `json:"secondaryVisualization,omitempty"`
	// Controls display of vertical line when an event occurs 
	ShowEventLines *bool `json:"showEventLines,omitempty"`
	// Controls the display of a sparkline in a single value chart 
	ShowSparkLine *bool `json:"showSparkLine,omitempty"`
	// Sort order of chart entries 
	SortBy *string `json:"sortBy,omitempty"`
	// Sort direction of heatmap chart entries 
	SortDirection *string `json:"sortDirection,omitempty"`
	// Custom property to sort on for a heatmap chart 
	SortProperty *string `json:"sortProperty,omitempty"`
	// Controls display of stacked plots 
	Stacked *bool `json:"stacked,omitempty"`
	Time *OptionsForTheTimeDisplayedInAChart `json:"time,omitempty"`
	// Controls timestamp display with values 
	TimeStampHidden *bool `json:"timeStampHidden,omitempty"`
	// Type of chart to display 
	Type string `json:"type"`
	// Measure to use when displaying or labeling values 
	UnitPrefix *string `json:"unitPrefix,omitempty"`
}

type _ChartOptions ChartOptions

// NewChartOptions instantiates a new ChartOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChartOptions(type_ string) *ChartOptions {
	this := ChartOptions{}
	var axisPrecision int32 = 3
	this.AxisPrecision = &axisPrecision
	var defaultPlotType string = "LineChart"
	this.DefaultPlotType = &defaultPlotType
	var hideMissingValues bool = false
	this.HideMissingValues = &hideMissingValues
	var includeZero bool = false
	this.IncludeZero = &includeZero
	var showEventLines bool = false
	this.ShowEventLines = &showEventLines
	var showSparkLine bool = false
	this.ShowSparkLine = &showSparkLine
	var sortDirection string = "Ascending"
	this.SortDirection = &sortDirection
	var stacked bool = false
	this.Stacked = &stacked
	var timeStampHidden bool = false
	this.TimeStampHidden = &timeStampHidden
	this.Type = type_
	var unitPrefix string = "Metric"
	this.UnitPrefix = &unitPrefix
	return &this
}

// NewChartOptionsWithDefaults instantiates a new ChartOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartOptionsWithDefaults() *ChartOptions {
	this := ChartOptions{}
	var axisPrecision int32 = 3
	this.AxisPrecision = &axisPrecision
	var defaultPlotType string = "LineChart"
	this.DefaultPlotType = &defaultPlotType
	var hideMissingValues bool = false
	this.HideMissingValues = &hideMissingValues
	var includeZero bool = false
	this.IncludeZero = &includeZero
	var showEventLines bool = false
	this.ShowEventLines = &showEventLines
	var showSparkLine bool = false
	this.ShowSparkLine = &showSparkLine
	var sortDirection string = "Ascending"
	this.SortDirection = &sortDirection
	var stacked bool = false
	this.Stacked = &stacked
	var timeStampHidden bool = false
	this.TimeStampHidden = &timeStampHidden
	var unitPrefix string = "Metric"
	this.UnitPrefix = &unitPrefix
	return &this
}

// GetAreaChartOptions returns the AreaChartOptions field value if set, zero value otherwise.
func (o *ChartOptions) GetAreaChartOptions() PropertiesForAreaCharts {
	if o == nil || IsNil(o.AreaChartOptions) {
		var ret PropertiesForAreaCharts
		return ret
	}
	return *o.AreaChartOptions
}

// GetAreaChartOptionsOk returns a tuple with the AreaChartOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetAreaChartOptionsOk() (*PropertiesForAreaCharts, bool) {
	if o == nil || IsNil(o.AreaChartOptions) {
		return nil, false
	}
	return o.AreaChartOptions, true
}

// HasAreaChartOptions returns a boolean if a field has been set.
func (o *ChartOptions) HasAreaChartOptions() bool {
	if o != nil && !IsNil(o.AreaChartOptions) {
		return true
	}

	return false
}

// SetAreaChartOptions gets a reference to the given PropertiesForAreaCharts and assigns it to the AreaChartOptions field.
func (o *ChartOptions) SetAreaChartOptions(v PropertiesForAreaCharts) {
	o.AreaChartOptions = &v
}

// GetAxes returns the Axes field value if set, zero value otherwise.
func (o *ChartOptions) GetAxes() []ChartAxes {
	if o == nil || IsNil(o.Axes) {
		var ret []ChartAxes
		return ret
	}
	return o.Axes
}

// GetAxesOk returns a tuple with the Axes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetAxesOk() ([]ChartAxes, bool) {
	if o == nil || IsNil(o.Axes) {
		return nil, false
	}
	return o.Axes, true
}

// HasAxes returns a boolean if a field has been set.
func (o *ChartOptions) HasAxes() bool {
	if o != nil && !IsNil(o.Axes) {
		return true
	}

	return false
}

// SetAxes gets a reference to the given []ChartAxes and assigns it to the Axes field.
func (o *ChartOptions) SetAxes(v []ChartAxes) {
	o.Axes = v
}

// GetAxisPrecision returns the AxisPrecision field value if set, zero value otherwise.
func (o *ChartOptions) GetAxisPrecision() int32 {
	if o == nil || IsNil(o.AxisPrecision) {
		var ret int32
		return ret
	}
	return *o.AxisPrecision
}

// GetAxisPrecisionOk returns a tuple with the AxisPrecision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetAxisPrecisionOk() (*int32, bool) {
	if o == nil || IsNil(o.AxisPrecision) {
		return nil, false
	}
	return o.AxisPrecision, true
}

// HasAxisPrecision returns a boolean if a field has been set.
func (o *ChartOptions) HasAxisPrecision() bool {
	if o != nil && !IsNil(o.AxisPrecision) {
		return true
	}

	return false
}

// SetAxisPrecision gets a reference to the given int32 and assigns it to the AxisPrecision field.
func (o *ChartOptions) SetAxisPrecision(v int32) {
	o.AxisPrecision = &v
}

// GetColorBy returns the ColorBy field value if set, zero value otherwise.
func (o *ChartOptions) GetColorBy() string {
	if o == nil || IsNil(o.ColorBy) {
		var ret string
		return ret
	}
	return *o.ColorBy
}

// GetColorByOk returns a tuple with the ColorBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetColorByOk() (*string, bool) {
	if o == nil || IsNil(o.ColorBy) {
		return nil, false
	}
	return o.ColorBy, true
}

// HasColorBy returns a boolean if a field has been set.
func (o *ChartOptions) HasColorBy() bool {
	if o != nil && !IsNil(o.ColorBy) {
		return true
	}

	return false
}

// SetColorBy gets a reference to the given string and assigns it to the ColorBy field.
func (o *ChartOptions) SetColorBy(v string) {
	o.ColorBy = &v
}

// GetColorRange returns the ColorRange field value if set, zero value otherwise.
func (o *ChartOptions) GetColorRange() SpecifiesColorRangeOptionsForColoringAHeatmapChart {
	if o == nil || IsNil(o.ColorRange) {
		var ret SpecifiesColorRangeOptionsForColoringAHeatmapChart
		return ret
	}
	return *o.ColorRange
}

// GetColorRangeOk returns a tuple with the ColorRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetColorRangeOk() (*SpecifiesColorRangeOptionsForColoringAHeatmapChart, bool) {
	if o == nil || IsNil(o.ColorRange) {
		return nil, false
	}
	return o.ColorRange, true
}

// HasColorRange returns a boolean if a field has been set.
func (o *ChartOptions) HasColorRange() bool {
	if o != nil && !IsNil(o.ColorRange) {
		return true
	}

	return false
}

// SetColorRange gets a reference to the given SpecifiesColorRangeOptionsForColoringAHeatmapChart and assigns it to the ColorRange field.
func (o *ChartOptions) SetColorRange(v SpecifiesColorRangeOptionsForColoringAHeatmapChart) {
	o.ColorRange = &v
}

// GetColorScale returns the ColorScale field value if set, zero value otherwise.
func (o *ChartOptions) GetColorScale() SpecifiesHowToApplyTheRangeOfSpecifiedColorValuesToDataInAHeatmapChart {
	if o == nil || IsNil(o.ColorScale) {
		var ret SpecifiesHowToApplyTheRangeOfSpecifiedColorValuesToDataInAHeatmapChart
		return ret
	}
	return *o.ColorScale
}

// GetColorScaleOk returns a tuple with the ColorScale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetColorScaleOk() (*SpecifiesHowToApplyTheRangeOfSpecifiedColorValuesToDataInAHeatmapChart, bool) {
	if o == nil || IsNil(o.ColorScale) {
		return nil, false
	}
	return o.ColorScale, true
}

// HasColorScale returns a boolean if a field has been set.
func (o *ChartOptions) HasColorScale() bool {
	if o != nil && !IsNil(o.ColorScale) {
		return true
	}

	return false
}

// SetColorScale gets a reference to the given SpecifiesHowToApplyTheRangeOfSpecifiedColorValuesToDataInAHeatmapChart and assigns it to the ColorScale field.
func (o *ChartOptions) SetColorScale(v SpecifiesHowToApplyTheRangeOfSpecifiedColorValuesToDataInAHeatmapChart) {
	o.ColorScale = &v
}

// GetColorScale2 returns the ColorScale2 field value if set, zero value otherwise.
func (o *ChartOptions) GetColorScale2() []ChartSecondaryVisualization {
	if o == nil || IsNil(o.ColorScale2) {
		var ret []ChartSecondaryVisualization
		return ret
	}
	return o.ColorScale2
}

// GetColorScale2Ok returns a tuple with the ColorScale2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetColorScale2Ok() ([]ChartSecondaryVisualization, bool) {
	if o == nil || IsNil(o.ColorScale2) {
		return nil, false
	}
	return o.ColorScale2, true
}

// HasColorScale2 returns a boolean if a field has been set.
func (o *ChartOptions) HasColorScale2() bool {
	if o != nil && !IsNil(o.ColorScale2) {
		return true
	}

	return false
}

// SetColorScale2 gets a reference to the given []ChartSecondaryVisualization and assigns it to the ColorScale2 field.
func (o *ChartOptions) SetColorScale2(v []ChartSecondaryVisualization) {
	o.ColorScale2 = v
}

// GetDefaultPlotType returns the DefaultPlotType field value if set, zero value otherwise.
func (o *ChartOptions) GetDefaultPlotType() string {
	if o == nil || IsNil(o.DefaultPlotType) {
		var ret string
		return ret
	}
	return *o.DefaultPlotType
}

// GetDefaultPlotTypeOk returns a tuple with the DefaultPlotType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetDefaultPlotTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultPlotType) {
		return nil, false
	}
	return o.DefaultPlotType, true
}

// HasDefaultPlotType returns a boolean if a field has been set.
func (o *ChartOptions) HasDefaultPlotType() bool {
	if o != nil && !IsNil(o.DefaultPlotType) {
		return true
	}

	return false
}

// SetDefaultPlotType gets a reference to the given string and assigns it to the DefaultPlotType field.
func (o *ChartOptions) SetDefaultPlotType(v string) {
	o.DefaultPlotType = &v
}

// GetGroupBy returns the GroupBy field value if set, zero value otherwise.
func (o *ChartOptions) GetGroupBy() []string {
	if o == nil || IsNil(o.GroupBy) {
		var ret []string
		return ret
	}
	return o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetGroupByOk() ([]string, bool) {
	if o == nil || IsNil(o.GroupBy) {
		return nil, false
	}
	return o.GroupBy, true
}

// HasGroupBy returns a boolean if a field has been set.
func (o *ChartOptions) HasGroupBy() bool {
	if o != nil && !IsNil(o.GroupBy) {
		return true
	}

	return false
}

// SetGroupBy gets a reference to the given []string and assigns it to the GroupBy field.
func (o *ChartOptions) SetGroupBy(v []string) {
	o.GroupBy = v
}

// GetGroupBySort returns the GroupBySort field value if set, zero value otherwise.
func (o *ChartOptions) GetGroupBySort() string {
	if o == nil || IsNil(o.GroupBySort) {
		var ret string
		return ret
	}
	return *o.GroupBySort
}

// GetGroupBySortOk returns a tuple with the GroupBySort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetGroupBySortOk() (*string, bool) {
	if o == nil || IsNil(o.GroupBySort) {
		return nil, false
	}
	return o.GroupBySort, true
}

// HasGroupBySort returns a boolean if a field has been set.
func (o *ChartOptions) HasGroupBySort() bool {
	if o != nil && !IsNil(o.GroupBySort) {
		return true
	}

	return false
}

// SetGroupBySort gets a reference to the given string and assigns it to the GroupBySort field.
func (o *ChartOptions) SetGroupBySort(v string) {
	o.GroupBySort = &v
}

// GetHideMissingValues returns the HideMissingValues field value if set, zero value otherwise.
func (o *ChartOptions) GetHideMissingValues() bool {
	if o == nil || IsNil(o.HideMissingValues) {
		var ret bool
		return ret
	}
	return *o.HideMissingValues
}

// GetHideMissingValuesOk returns a tuple with the HideMissingValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetHideMissingValuesOk() (*bool, bool) {
	if o == nil || IsNil(o.HideMissingValues) {
		return nil, false
	}
	return o.HideMissingValues, true
}

// HasHideMissingValues returns a boolean if a field has been set.
func (o *ChartOptions) HasHideMissingValues() bool {
	if o != nil && !IsNil(o.HideMissingValues) {
		return true
	}

	return false
}

// SetHideMissingValues gets a reference to the given bool and assigns it to the HideMissingValues field.
func (o *ChartOptions) SetHideMissingValues(v bool) {
	o.HideMissingValues = &v
}

// GetHistogramChartOptions returns the HistogramChartOptions field value if set, zero value otherwise.
func (o *ChartOptions) GetHistogramChartOptions() ChartOptionsHistogramChartOptions {
	if o == nil || IsNil(o.HistogramChartOptions) {
		var ret ChartOptionsHistogramChartOptions
		return ret
	}
	return *o.HistogramChartOptions
}

// GetHistogramChartOptionsOk returns a tuple with the HistogramChartOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetHistogramChartOptionsOk() (*ChartOptionsHistogramChartOptions, bool) {
	if o == nil || IsNil(o.HistogramChartOptions) {
		return nil, false
	}
	return o.HistogramChartOptions, true
}

// HasHistogramChartOptions returns a boolean if a field has been set.
func (o *ChartOptions) HasHistogramChartOptions() bool {
	if o != nil && !IsNil(o.HistogramChartOptions) {
		return true
	}

	return false
}

// SetHistogramChartOptions gets a reference to the given ChartOptionsHistogramChartOptions and assigns it to the HistogramChartOptions field.
func (o *ChartOptions) SetHistogramChartOptions(v ChartOptionsHistogramChartOptions) {
	o.HistogramChartOptions = &v
}

// GetIncludeZero returns the IncludeZero field value if set, zero value otherwise.
func (o *ChartOptions) GetIncludeZero() bool {
	if o == nil || IsNil(o.IncludeZero) {
		var ret bool
		return ret
	}
	return *o.IncludeZero
}

// GetIncludeZeroOk returns a tuple with the IncludeZero field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetIncludeZeroOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeZero) {
		return nil, false
	}
	return o.IncludeZero, true
}

// HasIncludeZero returns a boolean if a field has been set.
func (o *ChartOptions) HasIncludeZero() bool {
	if o != nil && !IsNil(o.IncludeZero) {
		return true
	}

	return false
}

// SetIncludeZero gets a reference to the given bool and assigns it to the IncludeZero field.
func (o *ChartOptions) SetIncludeZero(v bool) {
	o.IncludeZero = &v
}

// GetLegendOptions returns the LegendOptions field value if set, zero value otherwise.
func (o *ChartOptions) GetLegendOptions() SetsTableOptions {
	if o == nil || IsNil(o.LegendOptions) {
		var ret SetsTableOptions
		return ret
	}
	return *o.LegendOptions
}

// GetLegendOptionsOk returns a tuple with the LegendOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetLegendOptionsOk() (*SetsTableOptions, bool) {
	if o == nil || IsNil(o.LegendOptions) {
		return nil, false
	}
	return o.LegendOptions, true
}

// HasLegendOptions returns a boolean if a field has been set.
func (o *ChartOptions) HasLegendOptions() bool {
	if o != nil && !IsNil(o.LegendOptions) {
		return true
	}

	return false
}

// SetLegendOptions gets a reference to the given SetsTableOptions and assigns it to the LegendOptions field.
func (o *ChartOptions) SetLegendOptions(v SetsTableOptions) {
	o.LegendOptions = &v
}

// GetLineChartOptions returns the LineChartOptions field value if set, zero value otherwise.
func (o *ChartOptions) GetLineChartOptions() OptionsForALineChart {
	if o == nil || IsNil(o.LineChartOptions) {
		var ret OptionsForALineChart
		return ret
	}
	return *o.LineChartOptions
}

// GetLineChartOptionsOk returns a tuple with the LineChartOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetLineChartOptionsOk() (*OptionsForALineChart, bool) {
	if o == nil || IsNil(o.LineChartOptions) {
		return nil, false
	}
	return o.LineChartOptions, true
}

// HasLineChartOptions returns a boolean if a field has been set.
func (o *ChartOptions) HasLineChartOptions() bool {
	if o != nil && !IsNil(o.LineChartOptions) {
		return true
	}

	return false
}

// SetLineChartOptions gets a reference to the given OptionsForALineChart and assigns it to the LineChartOptions field.
func (o *ChartOptions) SetLineChartOptions(v OptionsForALineChart) {
	o.LineChartOptions = &v
}

// GetMarkdown returns the Markdown field value if set, zero value otherwise.
func (o *ChartOptions) GetMarkdown() string {
	if o == nil || IsNil(o.Markdown) {
		var ret string
		return ret
	}
	return *o.Markdown
}

// GetMarkdownOk returns a tuple with the Markdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetMarkdownOk() (*string, bool) {
	if o == nil || IsNil(o.Markdown) {
		return nil, false
	}
	return o.Markdown, true
}

// HasMarkdown returns a boolean if a field has been set.
func (o *ChartOptions) HasMarkdown() bool {
	if o != nil && !IsNil(o.Markdown) {
		return true
	}

	return false
}

// SetMarkdown gets a reference to the given string and assigns it to the Markdown field.
func (o *ChartOptions) SetMarkdown(v string) {
	o.Markdown = &v
}

// GetMaximumPrecision returns the MaximumPrecision field value if set, zero value otherwise.
func (o *ChartOptions) GetMaximumPrecision() int32 {
	if o == nil || IsNil(o.MaximumPrecision) {
		var ret int32
		return ret
	}
	return *o.MaximumPrecision
}

// GetMaximumPrecisionOk returns a tuple with the MaximumPrecision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetMaximumPrecisionOk() (*int32, bool) {
	if o == nil || IsNil(o.MaximumPrecision) {
		return nil, false
	}
	return o.MaximumPrecision, true
}

// HasMaximumPrecision returns a boolean if a field has been set.
func (o *ChartOptions) HasMaximumPrecision() bool {
	if o != nil && !IsNil(o.MaximumPrecision) {
		return true
	}

	return false
}

// SetMaximumPrecision gets a reference to the given int32 and assigns it to the MaximumPrecision field.
func (o *ChartOptions) SetMaximumPrecision(v int32) {
	o.MaximumPrecision = &v
}

// GetOnChartLegendOptions returns the OnChartLegendOptions field value if set, zero value otherwise.
func (o *ChartOptions) GetOnChartLegendOptions() DisplayOptionsForTheChartLegend {
	if o == nil || IsNil(o.OnChartLegendOptions) {
		var ret DisplayOptionsForTheChartLegend
		return ret
	}
	return *o.OnChartLegendOptions
}

// GetOnChartLegendOptionsOk returns a tuple with the OnChartLegendOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetOnChartLegendOptionsOk() (*DisplayOptionsForTheChartLegend, bool) {
	if o == nil || IsNil(o.OnChartLegendOptions) {
		return nil, false
	}
	return o.OnChartLegendOptions, true
}

// HasOnChartLegendOptions returns a boolean if a field has been set.
func (o *ChartOptions) HasOnChartLegendOptions() bool {
	if o != nil && !IsNil(o.OnChartLegendOptions) {
		return true
	}

	return false
}

// SetOnChartLegendOptions gets a reference to the given DisplayOptionsForTheChartLegend and assigns it to the OnChartLegendOptions field.
func (o *ChartOptions) SetOnChartLegendOptions(v DisplayOptionsForTheChartLegend) {
	o.OnChartLegendOptions = &v
}

// GetProgramOptions returns the ProgramOptions field value if set, zero value otherwise.
func (o *ChartOptions) GetProgramOptions() GeneralOptionsForTheChart {
	if o == nil || IsNil(o.ProgramOptions) {
		var ret GeneralOptionsForTheChart
		return ret
	}
	return *o.ProgramOptions
}

// GetProgramOptionsOk returns a tuple with the ProgramOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetProgramOptionsOk() (*GeneralOptionsForTheChart, bool) {
	if o == nil || IsNil(o.ProgramOptions) {
		return nil, false
	}
	return o.ProgramOptions, true
}

// HasProgramOptions returns a boolean if a field has been set.
func (o *ChartOptions) HasProgramOptions() bool {
	if o != nil && !IsNil(o.ProgramOptions) {
		return true
	}

	return false
}

// SetProgramOptions gets a reference to the given GeneralOptionsForTheChart and assigns it to the ProgramOptions field.
func (o *ChartOptions) SetProgramOptions(v GeneralOptionsForTheChart) {
	o.ProgramOptions = &v
}

// GetPublishLabelOptions returns the PublishLabelOptions field value if set, zero value otherwise.
func (o *ChartOptions) GetPublishLabelOptions() []ChartPublishLabelOptions {
	if o == nil || IsNil(o.PublishLabelOptions) {
		var ret []ChartPublishLabelOptions
		return ret
	}
	return o.PublishLabelOptions
}

// GetPublishLabelOptionsOk returns a tuple with the PublishLabelOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetPublishLabelOptionsOk() ([]ChartPublishLabelOptions, bool) {
	if o == nil || IsNil(o.PublishLabelOptions) {
		return nil, false
	}
	return o.PublishLabelOptions, true
}

// HasPublishLabelOptions returns a boolean if a field has been set.
func (o *ChartOptions) HasPublishLabelOptions() bool {
	if o != nil && !IsNil(o.PublishLabelOptions) {
		return true
	}

	return false
}

// SetPublishLabelOptions gets a reference to the given []ChartPublishLabelOptions and assigns it to the PublishLabelOptions field.
func (o *ChartOptions) SetPublishLabelOptions(v []ChartPublishLabelOptions) {
	o.PublishLabelOptions = v
}

// GetRefreshInterval returns the RefreshInterval field value if set, zero value otherwise.
func (o *ChartOptions) GetRefreshInterval() int32 {
	if o == nil || IsNil(o.RefreshInterval) {
		var ret int32
		return ret
	}
	return *o.RefreshInterval
}

// GetRefreshIntervalOk returns a tuple with the RefreshInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetRefreshIntervalOk() (*int32, bool) {
	if o == nil || IsNil(o.RefreshInterval) {
		return nil, false
	}
	return o.RefreshInterval, true
}

// HasRefreshInterval returns a boolean if a field has been set.
func (o *ChartOptions) HasRefreshInterval() bool {
	if o != nil && !IsNil(o.RefreshInterval) {
		return true
	}

	return false
}

// SetRefreshInterval gets a reference to the given int32 and assigns it to the RefreshInterval field.
func (o *ChartOptions) SetRefreshInterval(v int32) {
	o.RefreshInterval = &v
}

// GetSecondaryVisualization returns the SecondaryVisualization field value if set, zero value otherwise.
func (o *ChartOptions) GetSecondaryVisualization() string {
	if o == nil || IsNil(o.SecondaryVisualization) {
		var ret string
		return ret
	}
	return *o.SecondaryVisualization
}

// GetSecondaryVisualizationOk returns a tuple with the SecondaryVisualization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetSecondaryVisualizationOk() (*string, bool) {
	if o == nil || IsNil(o.SecondaryVisualization) {
		return nil, false
	}
	return o.SecondaryVisualization, true
}

// HasSecondaryVisualization returns a boolean if a field has been set.
func (o *ChartOptions) HasSecondaryVisualization() bool {
	if o != nil && !IsNil(o.SecondaryVisualization) {
		return true
	}

	return false
}

// SetSecondaryVisualization gets a reference to the given string and assigns it to the SecondaryVisualization field.
func (o *ChartOptions) SetSecondaryVisualization(v string) {
	o.SecondaryVisualization = &v
}

// GetShowEventLines returns the ShowEventLines field value if set, zero value otherwise.
func (o *ChartOptions) GetShowEventLines() bool {
	if o == nil || IsNil(o.ShowEventLines) {
		var ret bool
		return ret
	}
	return *o.ShowEventLines
}

// GetShowEventLinesOk returns a tuple with the ShowEventLines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetShowEventLinesOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowEventLines) {
		return nil, false
	}
	return o.ShowEventLines, true
}

// HasShowEventLines returns a boolean if a field has been set.
func (o *ChartOptions) HasShowEventLines() bool {
	if o != nil && !IsNil(o.ShowEventLines) {
		return true
	}

	return false
}

// SetShowEventLines gets a reference to the given bool and assigns it to the ShowEventLines field.
func (o *ChartOptions) SetShowEventLines(v bool) {
	o.ShowEventLines = &v
}

// GetShowSparkLine returns the ShowSparkLine field value if set, zero value otherwise.
func (o *ChartOptions) GetShowSparkLine() bool {
	if o == nil || IsNil(o.ShowSparkLine) {
		var ret bool
		return ret
	}
	return *o.ShowSparkLine
}

// GetShowSparkLineOk returns a tuple with the ShowSparkLine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetShowSparkLineOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowSparkLine) {
		return nil, false
	}
	return o.ShowSparkLine, true
}

// HasShowSparkLine returns a boolean if a field has been set.
func (o *ChartOptions) HasShowSparkLine() bool {
	if o != nil && !IsNil(o.ShowSparkLine) {
		return true
	}

	return false
}

// SetShowSparkLine gets a reference to the given bool and assigns it to the ShowSparkLine field.
func (o *ChartOptions) SetShowSparkLine(v bool) {
	o.ShowSparkLine = &v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise.
func (o *ChartOptions) GetSortBy() string {
	if o == nil || IsNil(o.SortBy) {
		var ret string
		return ret
	}
	return *o.SortBy
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetSortByOk() (*string, bool) {
	if o == nil || IsNil(o.SortBy) {
		return nil, false
	}
	return o.SortBy, true
}

// HasSortBy returns a boolean if a field has been set.
func (o *ChartOptions) HasSortBy() bool {
	if o != nil && !IsNil(o.SortBy) {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given string and assigns it to the SortBy field.
func (o *ChartOptions) SetSortBy(v string) {
	o.SortBy = &v
}

// GetSortDirection returns the SortDirection field value if set, zero value otherwise.
func (o *ChartOptions) GetSortDirection() string {
	if o == nil || IsNil(o.SortDirection) {
		var ret string
		return ret
	}
	return *o.SortDirection
}

// GetSortDirectionOk returns a tuple with the SortDirection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetSortDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.SortDirection) {
		return nil, false
	}
	return o.SortDirection, true
}

// HasSortDirection returns a boolean if a field has been set.
func (o *ChartOptions) HasSortDirection() bool {
	if o != nil && !IsNil(o.SortDirection) {
		return true
	}

	return false
}

// SetSortDirection gets a reference to the given string and assigns it to the SortDirection field.
func (o *ChartOptions) SetSortDirection(v string) {
	o.SortDirection = &v
}

// GetSortProperty returns the SortProperty field value if set, zero value otherwise.
func (o *ChartOptions) GetSortProperty() string {
	if o == nil || IsNil(o.SortProperty) {
		var ret string
		return ret
	}
	return *o.SortProperty
}

// GetSortPropertyOk returns a tuple with the SortProperty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetSortPropertyOk() (*string, bool) {
	if o == nil || IsNil(o.SortProperty) {
		return nil, false
	}
	return o.SortProperty, true
}

// HasSortProperty returns a boolean if a field has been set.
func (o *ChartOptions) HasSortProperty() bool {
	if o != nil && !IsNil(o.SortProperty) {
		return true
	}

	return false
}

// SetSortProperty gets a reference to the given string and assigns it to the SortProperty field.
func (o *ChartOptions) SetSortProperty(v string) {
	o.SortProperty = &v
}

// GetStacked returns the Stacked field value if set, zero value otherwise.
func (o *ChartOptions) GetStacked() bool {
	if o == nil || IsNil(o.Stacked) {
		var ret bool
		return ret
	}
	return *o.Stacked
}

// GetStackedOk returns a tuple with the Stacked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetStackedOk() (*bool, bool) {
	if o == nil || IsNil(o.Stacked) {
		return nil, false
	}
	return o.Stacked, true
}

// HasStacked returns a boolean if a field has been set.
func (o *ChartOptions) HasStacked() bool {
	if o != nil && !IsNil(o.Stacked) {
		return true
	}

	return false
}

// SetStacked gets a reference to the given bool and assigns it to the Stacked field.
func (o *ChartOptions) SetStacked(v bool) {
	o.Stacked = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *ChartOptions) GetTime() OptionsForTheTimeDisplayedInAChart {
	if o == nil || IsNil(o.Time) {
		var ret OptionsForTheTimeDisplayedInAChart
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetTimeOk() (*OptionsForTheTimeDisplayedInAChart, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *ChartOptions) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given OptionsForTheTimeDisplayedInAChart and assigns it to the Time field.
func (o *ChartOptions) SetTime(v OptionsForTheTimeDisplayedInAChart) {
	o.Time = &v
}

// GetTimeStampHidden returns the TimeStampHidden field value if set, zero value otherwise.
func (o *ChartOptions) GetTimeStampHidden() bool {
	if o == nil || IsNil(o.TimeStampHidden) {
		var ret bool
		return ret
	}
	return *o.TimeStampHidden
}

// GetTimeStampHiddenOk returns a tuple with the TimeStampHidden field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetTimeStampHiddenOk() (*bool, bool) {
	if o == nil || IsNil(o.TimeStampHidden) {
		return nil, false
	}
	return o.TimeStampHidden, true
}

// HasTimeStampHidden returns a boolean if a field has been set.
func (o *ChartOptions) HasTimeStampHidden() bool {
	if o != nil && !IsNil(o.TimeStampHidden) {
		return true
	}

	return false
}

// SetTimeStampHidden gets a reference to the given bool and assigns it to the TimeStampHidden field.
func (o *ChartOptions) SetTimeStampHidden(v bool) {
	o.TimeStampHidden = &v
}

// GetType returns the Type field value
func (o *ChartOptions) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ChartOptions) SetType(v string) {
	o.Type = v
}

// GetUnitPrefix returns the UnitPrefix field value if set, zero value otherwise.
func (o *ChartOptions) GetUnitPrefix() string {
	if o == nil || IsNil(o.UnitPrefix) {
		var ret string
		return ret
	}
	return *o.UnitPrefix
}

// GetUnitPrefixOk returns a tuple with the UnitPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptions) GetUnitPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.UnitPrefix) {
		return nil, false
	}
	return o.UnitPrefix, true
}

// HasUnitPrefix returns a boolean if a field has been set.
func (o *ChartOptions) HasUnitPrefix() bool {
	if o != nil && !IsNil(o.UnitPrefix) {
		return true
	}

	return false
}

// SetUnitPrefix gets a reference to the given string and assigns it to the UnitPrefix field.
func (o *ChartOptions) SetUnitPrefix(v string) {
	o.UnitPrefix = &v
}

func (o ChartOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChartOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AreaChartOptions) {
		toSerialize["areaChartOptions"] = o.AreaChartOptions
	}
	if !IsNil(o.Axes) {
		toSerialize["axes"] = o.Axes
	}
	if !IsNil(o.AxisPrecision) {
		toSerialize["axisPrecision"] = o.AxisPrecision
	}
	if !IsNil(o.ColorBy) {
		toSerialize["colorBy"] = o.ColorBy
	}
	if !IsNil(o.ColorRange) {
		toSerialize["colorRange"] = o.ColorRange
	}
	if !IsNil(o.ColorScale) {
		toSerialize["colorScale"] = o.ColorScale
	}
	if !IsNil(o.ColorScale2) {
		toSerialize["colorScale2"] = o.ColorScale2
	}
	if !IsNil(o.DefaultPlotType) {
		toSerialize["defaultPlotType"] = o.DefaultPlotType
	}
	if !IsNil(o.GroupBy) {
		toSerialize["groupBy"] = o.GroupBy
	}
	if !IsNil(o.GroupBySort) {
		toSerialize["groupBySort"] = o.GroupBySort
	}
	if !IsNil(o.HideMissingValues) {
		toSerialize["hideMissingValues"] = o.HideMissingValues
	}
	if !IsNil(o.HistogramChartOptions) {
		toSerialize["histogramChartOptions"] = o.HistogramChartOptions
	}
	if !IsNil(o.IncludeZero) {
		toSerialize["includeZero"] = o.IncludeZero
	}
	if !IsNil(o.LegendOptions) {
		toSerialize["legendOptions"] = o.LegendOptions
	}
	if !IsNil(o.LineChartOptions) {
		toSerialize["lineChartOptions"] = o.LineChartOptions
	}
	if !IsNil(o.Markdown) {
		toSerialize["markdown"] = o.Markdown
	}
	if !IsNil(o.MaximumPrecision) {
		toSerialize["maximumPrecision"] = o.MaximumPrecision
	}
	if !IsNil(o.OnChartLegendOptions) {
		toSerialize["onChartLegendOptions"] = o.OnChartLegendOptions
	}
	if !IsNil(o.ProgramOptions) {
		toSerialize["programOptions"] = o.ProgramOptions
	}
	if !IsNil(o.PublishLabelOptions) {
		toSerialize["publishLabelOptions"] = o.PublishLabelOptions
	}
	if !IsNil(o.RefreshInterval) {
		toSerialize["refreshInterval"] = o.RefreshInterval
	}
	if !IsNil(o.SecondaryVisualization) {
		toSerialize["secondaryVisualization"] = o.SecondaryVisualization
	}
	if !IsNil(o.ShowEventLines) {
		toSerialize["showEventLines"] = o.ShowEventLines
	}
	if !IsNil(o.ShowSparkLine) {
		toSerialize["showSparkLine"] = o.ShowSparkLine
	}
	if !IsNil(o.SortBy) {
		toSerialize["sortBy"] = o.SortBy
	}
	if !IsNil(o.SortDirection) {
		toSerialize["sortDirection"] = o.SortDirection
	}
	if !IsNil(o.SortProperty) {
		toSerialize["sortProperty"] = o.SortProperty
	}
	if !IsNil(o.Stacked) {
		toSerialize["stacked"] = o.Stacked
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.TimeStampHidden) {
		toSerialize["timeStampHidden"] = o.TimeStampHidden
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.UnitPrefix) {
		toSerialize["unitPrefix"] = o.UnitPrefix
	}
	return toSerialize, nil
}

func (o *ChartOptions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChartOptions := _ChartOptions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChartOptions)

	if err != nil {
		return err
	}

	*o = ChartOptions(varChartOptions)

	return err
}

type NullableChartOptions struct {
	value *ChartOptions
	isSet bool
}

func (v NullableChartOptions) Get() *ChartOptions {
	return v.value
}

func (v *NullableChartOptions) Set(val *ChartOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableChartOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableChartOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChartOptions(val *ChartOptions) *NullableChartOptions {
	return &NullableChartOptions{value: val, isSet: true}
}

func (v NullableChartOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChartOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


