/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the DashboardChartsFiltersTime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardChartsFiltersTime{}

// DashboardChartsFiltersTime Time range to show in all charts in the dashboard 
type DashboardChartsFiltersTime struct {
	// End of the time range to show for the charts in this dashboard 
	End *string `json:"end,omitempty"`
	// Start of the time range to show for the charts in this dashboard. 
	Start *string `json:"start,omitempty"`
}

// NewDashboardChartsFiltersTime instantiates a new DashboardChartsFiltersTime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardChartsFiltersTime() *DashboardChartsFiltersTime {
	this := DashboardChartsFiltersTime{}
	return &this
}

// NewDashboardChartsFiltersTimeWithDefaults instantiates a new DashboardChartsFiltersTime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardChartsFiltersTimeWithDefaults() *DashboardChartsFiltersTime {
	this := DashboardChartsFiltersTime{}
	return &this
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *DashboardChartsFiltersTime) GetEnd() string {
	if o == nil || IsNil(o.End) {
		var ret string
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardChartsFiltersTime) GetEndOk() (*string, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *DashboardChartsFiltersTime) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given string and assigns it to the End field.
func (o *DashboardChartsFiltersTime) SetEnd(v string) {
	o.End = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *DashboardChartsFiltersTime) GetStart() string {
	if o == nil || IsNil(o.Start) {
		var ret string
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardChartsFiltersTime) GetStartOk() (*string, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *DashboardChartsFiltersTime) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given string and assigns it to the Start field.
func (o *DashboardChartsFiltersTime) SetStart(v string) {
	o.Start = &v
}

func (o DashboardChartsFiltersTime) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardChartsFiltersTime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	return toSerialize, nil
}

type NullableDashboardChartsFiltersTime struct {
	value *DashboardChartsFiltersTime
	isSet bool
}

func (v NullableDashboardChartsFiltersTime) Get() *DashboardChartsFiltersTime {
	return v.value
}

func (v *NullableDashboardChartsFiltersTime) Set(val *DashboardChartsFiltersTime) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardChartsFiltersTime) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardChartsFiltersTime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardChartsFiltersTime(val *DashboardChartsFiltersTime) *NullableDashboardChartsFiltersTime {
	return &NullableDashboardChartsFiltersTime{value: val, isSet: true}
}

func (v NullableDashboardChartsFiltersTime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardChartsFiltersTime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


