/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DashboardChartsWebUIFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardChartsWebUIFilter{}

// DashboardChartsWebUIFilter Filter that compares a dimension or property to a value 
type DashboardChartsWebUIFilter struct {
	// Label for the filter 
	Alias *string `json:"alias,omitempty"`
	// List of of values to place at the top of the values dropdown list 
	PreferredSuggestions []string `json:"preferredSuggestions,omitempty"`
	// Custom property or dimension name 
	Property string `json:"property"`
	// Controls display of chart data 
	Required *bool `json:"required,omitempty"`
	// Controls values allowed in the filter 
	Restricted *bool `json:"restricted,omitempty"`
	// List of values to compare to the dimension or custom property 
	Value []string `json:"value"`
}

type _DashboardChartsWebUIFilter DashboardChartsWebUIFilter

// NewDashboardChartsWebUIFilter instantiates a new DashboardChartsWebUIFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardChartsWebUIFilter(property string, value []string) *DashboardChartsWebUIFilter {
	this := DashboardChartsWebUIFilter{}
	this.Property = property
	var required bool = false
	this.Required = &required
	var restricted bool = false
	this.Restricted = &restricted
	this.Value = value
	return &this
}

// NewDashboardChartsWebUIFilterWithDefaults instantiates a new DashboardChartsWebUIFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardChartsWebUIFilterWithDefaults() *DashboardChartsWebUIFilter {
	this := DashboardChartsWebUIFilter{}
	var required bool = false
	this.Required = &required
	var restricted bool = false
	this.Restricted = &restricted
	return &this
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *DashboardChartsWebUIFilter) GetAlias() string {
	if o == nil || IsNil(o.Alias) {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardChartsWebUIFilter) GetAliasOk() (*string, bool) {
	if o == nil || IsNil(o.Alias) {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *DashboardChartsWebUIFilter) HasAlias() bool {
	if o != nil && !IsNil(o.Alias) {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *DashboardChartsWebUIFilter) SetAlias(v string) {
	o.Alias = &v
}

// GetPreferredSuggestions returns the PreferredSuggestions field value if set, zero value otherwise.
func (o *DashboardChartsWebUIFilter) GetPreferredSuggestions() []string {
	if o == nil || IsNil(o.PreferredSuggestions) {
		var ret []string
		return ret
	}
	return o.PreferredSuggestions
}

// GetPreferredSuggestionsOk returns a tuple with the PreferredSuggestions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardChartsWebUIFilter) GetPreferredSuggestionsOk() ([]string, bool) {
	if o == nil || IsNil(o.PreferredSuggestions) {
		return nil, false
	}
	return o.PreferredSuggestions, true
}

// HasPreferredSuggestions returns a boolean if a field has been set.
func (o *DashboardChartsWebUIFilter) HasPreferredSuggestions() bool {
	if o != nil && !IsNil(o.PreferredSuggestions) {
		return true
	}

	return false
}

// SetPreferredSuggestions gets a reference to the given []string and assigns it to the PreferredSuggestions field.
func (o *DashboardChartsWebUIFilter) SetPreferredSuggestions(v []string) {
	o.PreferredSuggestions = v
}

// GetProperty returns the Property field value
func (o *DashboardChartsWebUIFilter) GetProperty() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Property
}

// GetPropertyOk returns a tuple with the Property field value
// and a boolean to check if the value has been set.
func (o *DashboardChartsWebUIFilter) GetPropertyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Property, true
}

// SetProperty sets field value
func (o *DashboardChartsWebUIFilter) SetProperty(v string) {
	o.Property = v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *DashboardChartsWebUIFilter) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardChartsWebUIFilter) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *DashboardChartsWebUIFilter) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *DashboardChartsWebUIFilter) SetRequired(v bool) {
	o.Required = &v
}

// GetRestricted returns the Restricted field value if set, zero value otherwise.
func (o *DashboardChartsWebUIFilter) GetRestricted() bool {
	if o == nil || IsNil(o.Restricted) {
		var ret bool
		return ret
	}
	return *o.Restricted
}

// GetRestrictedOk returns a tuple with the Restricted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardChartsWebUIFilter) GetRestrictedOk() (*bool, bool) {
	if o == nil || IsNil(o.Restricted) {
		return nil, false
	}
	return o.Restricted, true
}

// HasRestricted returns a boolean if a field has been set.
func (o *DashboardChartsWebUIFilter) HasRestricted() bool {
	if o != nil && !IsNil(o.Restricted) {
		return true
	}

	return false
}

// SetRestricted gets a reference to the given bool and assigns it to the Restricted field.
func (o *DashboardChartsWebUIFilter) SetRestricted(v bool) {
	o.Restricted = &v
}

// GetValue returns the Value field value
func (o *DashboardChartsWebUIFilter) GetValue() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *DashboardChartsWebUIFilter) GetValueOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *DashboardChartsWebUIFilter) SetValue(v []string) {
	o.Value = v
}

func (o DashboardChartsWebUIFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardChartsWebUIFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Alias) {
		toSerialize["alias"] = o.Alias
	}
	if !IsNil(o.PreferredSuggestions) {
		toSerialize["preferredSuggestions"] = o.PreferredSuggestions
	}
	toSerialize["property"] = o.Property
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.Restricted) {
		toSerialize["restricted"] = o.Restricted
	}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *DashboardChartsWebUIFilter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"property",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDashboardChartsWebUIFilter := _DashboardChartsWebUIFilter{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDashboardChartsWebUIFilter)

	if err != nil {
		return err
	}

	*o = DashboardChartsWebUIFilter(varDashboardChartsWebUIFilter)

	return err
}

type NullableDashboardChartsWebUIFilter struct {
	value *DashboardChartsWebUIFilter
	isSet bool
}

func (v NullableDashboardChartsWebUIFilter) Get() *DashboardChartsWebUIFilter {
	return v.value
}

func (v *NullableDashboardChartsWebUIFilter) Set(val *DashboardChartsWebUIFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardChartsWebUIFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardChartsWebUIFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardChartsWebUIFilter(val *DashboardChartsWebUIFilter) *NullableDashboardChartsWebUIFilter {
	return &NullableDashboardChartsWebUIFilter{value: val, isSet: true}
}

func (v NullableDashboardChartsWebUIFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardChartsWebUIFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


