/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the DashboardEventSources type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardEventSources{}

// DashboardEventSources struct for DashboardEventSources
type DashboardEventSources struct {
	// Inverts the filter comparison 
	NOT *bool `json:"NOT,omitempty"`
	// Custom property or dimension for which you want to test the value 
	Property *string `json:"property,omitempty"`
	// List of values to test against the property or dimension 
	Value []string `json:"value,omitempty"`
}

// NewDashboardEventSources instantiates a new DashboardEventSources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardEventSources() *DashboardEventSources {
	this := DashboardEventSources{}
	var nOT bool = false
	this.NOT = &nOT
	return &this
}

// NewDashboardEventSourcesWithDefaults instantiates a new DashboardEventSources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardEventSourcesWithDefaults() *DashboardEventSources {
	this := DashboardEventSources{}
	var nOT bool = false
	this.NOT = &nOT
	return &this
}

// GetNOT returns the NOT field value if set, zero value otherwise.
func (o *DashboardEventSources) GetNOT() bool {
	if o == nil || IsNil(o.NOT) {
		var ret bool
		return ret
	}
	return *o.NOT
}

// GetNOTOk returns a tuple with the NOT field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardEventSources) GetNOTOk() (*bool, bool) {
	if o == nil || IsNil(o.NOT) {
		return nil, false
	}
	return o.NOT, true
}

// HasNOT returns a boolean if a field has been set.
func (o *DashboardEventSources) HasNOT() bool {
	if o != nil && !IsNil(o.NOT) {
		return true
	}

	return false
}

// SetNOT gets a reference to the given bool and assigns it to the NOT field.
func (o *DashboardEventSources) SetNOT(v bool) {
	o.NOT = &v
}

// GetProperty returns the Property field value if set, zero value otherwise.
func (o *DashboardEventSources) GetProperty() string {
	if o == nil || IsNil(o.Property) {
		var ret string
		return ret
	}
	return *o.Property
}

// GetPropertyOk returns a tuple with the Property field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardEventSources) GetPropertyOk() (*string, bool) {
	if o == nil || IsNil(o.Property) {
		return nil, false
	}
	return o.Property, true
}

// HasProperty returns a boolean if a field has been set.
func (o *DashboardEventSources) HasProperty() bool {
	if o != nil && !IsNil(o.Property) {
		return true
	}

	return false
}

// SetProperty gets a reference to the given string and assigns it to the Property field.
func (o *DashboardEventSources) SetProperty(v string) {
	o.Property = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *DashboardEventSources) GetValue() []string {
	if o == nil || IsNil(o.Value) {
		var ret []string
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardEventSources) GetValueOk() ([]string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *DashboardEventSources) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given []string and assigns it to the Value field.
func (o *DashboardEventSources) SetValue(v []string) {
	o.Value = v
}

func (o DashboardEventSources) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardEventSources) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NOT) {
		toSerialize["NOT"] = o.NOT
	}
	if !IsNil(o.Property) {
		toSerialize["property"] = o.Property
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableDashboardEventSources struct {
	value *DashboardEventSources
	isSet bool
}

func (v NullableDashboardEventSources) Get() *DashboardEventSources {
	return v.value
}

func (v *NullableDashboardEventSources) Set(val *DashboardEventSources) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardEventSources) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardEventSources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardEventSources(val *DashboardEventSources) *NullableDashboardEventSources {
	return &NullableDashboardEventSources{value: val, isSet: true}
}

func (v NullableDashboardEventSources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardEventSources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


