/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the DashboardAuthorizedWriters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardAuthorizedWriters{}

// DashboardAuthorizedWriters List of user and team IDs that can modify charts in this dashboard 
type DashboardAuthorizedWriters struct {
	// List of teams that can modify charts in this dashboard 
	Teams []string `json:"teams,omitempty"`
	// List of teams that can modify charts in this dashboard 
	Users []string `json:"users,omitempty"`
}

// NewDashboardAuthorizedWriters instantiates a new DashboardAuthorizedWriters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardAuthorizedWriters() *DashboardAuthorizedWriters {
	this := DashboardAuthorizedWriters{}
	return &this
}

// NewDashboardAuthorizedWritersWithDefaults instantiates a new DashboardAuthorizedWriters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardAuthorizedWritersWithDefaults() *DashboardAuthorizedWriters {
	this := DashboardAuthorizedWriters{}
	return &this
}

// GetTeams returns the Teams field value if set, zero value otherwise.
func (o *DashboardAuthorizedWriters) GetTeams() []string {
	if o == nil || IsNil(o.Teams) {
		var ret []string
		return ret
	}
	return o.Teams
}

// GetTeamsOk returns a tuple with the Teams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardAuthorizedWriters) GetTeamsOk() ([]string, bool) {
	if o == nil || IsNil(o.Teams) {
		return nil, false
	}
	return o.Teams, true
}

// HasTeams returns a boolean if a field has been set.
func (o *DashboardAuthorizedWriters) HasTeams() bool {
	if o != nil && !IsNil(o.Teams) {
		return true
	}

	return false
}

// SetTeams gets a reference to the given []string and assigns it to the Teams field.
func (o *DashboardAuthorizedWriters) SetTeams(v []string) {
	o.Teams = v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *DashboardAuthorizedWriters) GetUsers() []string {
	if o == nil || IsNil(o.Users) {
		var ret []string
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardAuthorizedWriters) GetUsersOk() ([]string, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *DashboardAuthorizedWriters) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []string and assigns it to the Users field.
func (o *DashboardAuthorizedWriters) SetUsers(v []string) {
	o.Users = v
}

func (o DashboardAuthorizedWriters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardAuthorizedWriters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Teams) {
		toSerialize["teams"] = o.Teams
	}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	return toSerialize, nil
}

type NullableDashboardAuthorizedWriters struct {
	value *DashboardAuthorizedWriters
	isSet bool
}

func (v NullableDashboardAuthorizedWriters) Get() *DashboardAuthorizedWriters {
	return v.value
}

func (v *NullableDashboardAuthorizedWriters) Set(val *DashboardAuthorizedWriters) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardAuthorizedWriters) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardAuthorizedWriters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardAuthorizedWriters(val *DashboardAuthorizedWriters) *NullableDashboardAuthorizedWriters {
	return &NullableDashboardAuthorizedWriters{value: val, isSet: true}
}

func (v NullableDashboardAuthorizedWriters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardAuthorizedWriters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


