/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the ColoringThreshold type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ColoringThreshold{}

// ColoringThreshold Single coloring threshold 
type ColoringThreshold struct {
	// Lower limit of the threshold 
	LowerLimit *int32 `json:"lowerLimit,omitempty"`
	// 0-based index that specifies which color in the gradient is assigned to the range bounded at the lower limit by this threshold 
	PaletteIndex *int64 `json:"paletteIndex,omitempty"`
}

// NewColoringThreshold instantiates a new ColoringThreshold object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewColoringThreshold() *ColoringThreshold {
	this := ColoringThreshold{}
	return &this
}

// NewColoringThresholdWithDefaults instantiates a new ColoringThreshold object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewColoringThresholdWithDefaults() *ColoringThreshold {
	this := ColoringThreshold{}
	return &this
}

// GetLowerLimit returns the LowerLimit field value if set, zero value otherwise.
func (o *ColoringThreshold) GetLowerLimit() int32 {
	if o == nil || IsNil(o.LowerLimit) {
		var ret int32
		return ret
	}
	return *o.LowerLimit
}

// GetLowerLimitOk returns a tuple with the LowerLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColoringThreshold) GetLowerLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.LowerLimit) {
		return nil, false
	}
	return o.LowerLimit, true
}

// HasLowerLimit returns a boolean if a field has been set.
func (o *ColoringThreshold) HasLowerLimit() bool {
	if o != nil && !IsNil(o.LowerLimit) {
		return true
	}

	return false
}

// SetLowerLimit gets a reference to the given int32 and assigns it to the LowerLimit field.
func (o *ColoringThreshold) SetLowerLimit(v int32) {
	o.LowerLimit = &v
}

// GetPaletteIndex returns the PaletteIndex field value if set, zero value otherwise.
func (o *ColoringThreshold) GetPaletteIndex() int64 {
	if o == nil || IsNil(o.PaletteIndex) {
		var ret int64
		return ret
	}
	return *o.PaletteIndex
}

// GetPaletteIndexOk returns a tuple with the PaletteIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColoringThreshold) GetPaletteIndexOk() (*int64, bool) {
	if o == nil || IsNil(o.PaletteIndex) {
		return nil, false
	}
	return o.PaletteIndex, true
}

// HasPaletteIndex returns a boolean if a field has been set.
func (o *ColoringThreshold) HasPaletteIndex() bool {
	if o != nil && !IsNil(o.PaletteIndex) {
		return true
	}

	return false
}

// SetPaletteIndex gets a reference to the given int64 and assigns it to the PaletteIndex field.
func (o *ColoringThreshold) SetPaletteIndex(v int64) {
	o.PaletteIndex = &v
}

func (o ColoringThreshold) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ColoringThreshold) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LowerLimit) {
		toSerialize["lowerLimit"] = o.LowerLimit
	}
	if !IsNil(o.PaletteIndex) {
		toSerialize["paletteIndex"] = o.PaletteIndex
	}
	return toSerialize, nil
}

type NullableColoringThreshold struct {
	value *ColoringThreshold
	isSet bool
}

func (v NullableColoringThreshold) Get() *ColoringThreshold {
	return v.value
}

func (v *NullableColoringThreshold) Set(val *ColoringThreshold) {
	v.value = val
	v.isSet = true
}

func (v NullableColoringThreshold) IsSet() bool {
	return v.isSet
}

func (v *NullableColoringThreshold) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableColoringThreshold(val *ColoringThreshold) *NullableColoringThreshold {
	return &NullableColoringThreshold{value: val, isSet: true}
}

func (v NullableColoringThreshold) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableColoringThreshold) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


