/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the UpdateNavigatorRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNavigatorRequest{}

// UpdateNavigatorRequest Properties you can overwrite in an Update Navigator request 
type UpdateNavigatorRequest struct {
	// Navigator alert query 
	AlertQuery *string `json:"alertQuery,omitempty"`
	// Navigator categories list 
	Categories []Category `json:"categories,omitempty"`
	// Navigator default group by  
	DefaultGroupBy *string `json:"defaultGroupBy,omitempty"`
	// Navigator display name 
	DisplayName *string `json:"displayName,omitempty"`
	// Navigator metrics information 
	EntityMetrics []Metric `json:"entityMetrics,omitempty"`
	// Navigator system ID 
	Id *string `json:"id,omitempty"`
	// Navigator ID display name 
	IdDisplayName *string `json:"idDisplayName,omitempty"`
	// Array of dashboard IDs to use for instance display. Specific to GET /navigator. 
	InstanceDashboards []string `json:"instanceDashboards,omitempty"`
	// Instance description to display 
	InstanceDisplayText *string `json:"instanceDisplayText,omitempty"`
	// Navigator instance label 
	InstanceLabel *string `json:"instanceLabel,omitempty"`
	// List of columns in navigator 
	ListColumns []ListColumn `json:"listColumns,omitempty"`
	// Template for ID construction 
	PropertyIdentifierTemplate *string `json:"propertyIdentifierTemplate,omitempty"`
	// Properties shared by all instances 
	RequiredProperties []string `json:"requiredProperties,omitempty"`
	// Navigator system type identifiers 
	SystemTypes []string `json:"systemTypes,omitempty"`
	// Label for a summary metric 
	SummaryMetricLabel *string `json:"summaryMetricLabel,omitempty"`
	// SignalFlow program for summary metric 
	SummaryMetricProgramText *string `json:"summaryMetricProgramText,omitempty"`
	// A list of keys that appears in the tooltip 
	TooltipKeyList []TooltipKey `json:"tooltipKeyList,omitempty"`
}

// NewUpdateNavigatorRequest instantiates a new UpdateNavigatorRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNavigatorRequest() *UpdateNavigatorRequest {
	this := UpdateNavigatorRequest{}
	return &this
}

// NewUpdateNavigatorRequestWithDefaults instantiates a new UpdateNavigatorRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNavigatorRequestWithDefaults() *UpdateNavigatorRequest {
	this := UpdateNavigatorRequest{}
	return &this
}

// GetAlertQuery returns the AlertQuery field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetAlertQuery() string {
	if o == nil || IsNil(o.AlertQuery) {
		var ret string
		return ret
	}
	return *o.AlertQuery
}

// GetAlertQueryOk returns a tuple with the AlertQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetAlertQueryOk() (*string, bool) {
	if o == nil || IsNil(o.AlertQuery) {
		return nil, false
	}
	return o.AlertQuery, true
}

// HasAlertQuery returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasAlertQuery() bool {
	if o != nil && !IsNil(o.AlertQuery) {
		return true
	}

	return false
}

// SetAlertQuery gets a reference to the given string and assigns it to the AlertQuery field.
func (o *UpdateNavigatorRequest) SetAlertQuery(v string) {
	o.AlertQuery = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetCategories() []Category {
	if o == nil || IsNil(o.Categories) {
		var ret []Category
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetCategoriesOk() ([]Category, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []Category and assigns it to the Categories field.
func (o *UpdateNavigatorRequest) SetCategories(v []Category) {
	o.Categories = v
}

// GetDefaultGroupBy returns the DefaultGroupBy field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetDefaultGroupBy() string {
	if o == nil || IsNil(o.DefaultGroupBy) {
		var ret string
		return ret
	}
	return *o.DefaultGroupBy
}

// GetDefaultGroupByOk returns a tuple with the DefaultGroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetDefaultGroupByOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultGroupBy) {
		return nil, false
	}
	return o.DefaultGroupBy, true
}

// HasDefaultGroupBy returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasDefaultGroupBy() bool {
	if o != nil && !IsNil(o.DefaultGroupBy) {
		return true
	}

	return false
}

// SetDefaultGroupBy gets a reference to the given string and assigns it to the DefaultGroupBy field.
func (o *UpdateNavigatorRequest) SetDefaultGroupBy(v string) {
	o.DefaultGroupBy = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *UpdateNavigatorRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetEntityMetrics returns the EntityMetrics field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetEntityMetrics() []Metric {
	if o == nil || IsNil(o.EntityMetrics) {
		var ret []Metric
		return ret
	}
	return o.EntityMetrics
}

// GetEntityMetricsOk returns a tuple with the EntityMetrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetEntityMetricsOk() ([]Metric, bool) {
	if o == nil || IsNil(o.EntityMetrics) {
		return nil, false
	}
	return o.EntityMetrics, true
}

// HasEntityMetrics returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasEntityMetrics() bool {
	if o != nil && !IsNil(o.EntityMetrics) {
		return true
	}

	return false
}

// SetEntityMetrics gets a reference to the given []Metric and assigns it to the EntityMetrics field.
func (o *UpdateNavigatorRequest) SetEntityMetrics(v []Metric) {
	o.EntityMetrics = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UpdateNavigatorRequest) SetId(v string) {
	o.Id = &v
}

// GetIdDisplayName returns the IdDisplayName field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetIdDisplayName() string {
	if o == nil || IsNil(o.IdDisplayName) {
		var ret string
		return ret
	}
	return *o.IdDisplayName
}

// GetIdDisplayNameOk returns a tuple with the IdDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetIdDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.IdDisplayName) {
		return nil, false
	}
	return o.IdDisplayName, true
}

// HasIdDisplayName returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasIdDisplayName() bool {
	if o != nil && !IsNil(o.IdDisplayName) {
		return true
	}

	return false
}

// SetIdDisplayName gets a reference to the given string and assigns it to the IdDisplayName field.
func (o *UpdateNavigatorRequest) SetIdDisplayName(v string) {
	o.IdDisplayName = &v
}

// GetInstanceDashboards returns the InstanceDashboards field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetInstanceDashboards() []string {
	if o == nil || IsNil(o.InstanceDashboards) {
		var ret []string
		return ret
	}
	return o.InstanceDashboards
}

// GetInstanceDashboardsOk returns a tuple with the InstanceDashboards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetInstanceDashboardsOk() ([]string, bool) {
	if o == nil || IsNil(o.InstanceDashboards) {
		return nil, false
	}
	return o.InstanceDashboards, true
}

// HasInstanceDashboards returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasInstanceDashboards() bool {
	if o != nil && !IsNil(o.InstanceDashboards) {
		return true
	}

	return false
}

// SetInstanceDashboards gets a reference to the given []string and assigns it to the InstanceDashboards field.
func (o *UpdateNavigatorRequest) SetInstanceDashboards(v []string) {
	o.InstanceDashboards = v
}

// GetInstanceDisplayText returns the InstanceDisplayText field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetInstanceDisplayText() string {
	if o == nil || IsNil(o.InstanceDisplayText) {
		var ret string
		return ret
	}
	return *o.InstanceDisplayText
}

// GetInstanceDisplayTextOk returns a tuple with the InstanceDisplayText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetInstanceDisplayTextOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceDisplayText) {
		return nil, false
	}
	return o.InstanceDisplayText, true
}

// HasInstanceDisplayText returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasInstanceDisplayText() bool {
	if o != nil && !IsNil(o.InstanceDisplayText) {
		return true
	}

	return false
}

// SetInstanceDisplayText gets a reference to the given string and assigns it to the InstanceDisplayText field.
func (o *UpdateNavigatorRequest) SetInstanceDisplayText(v string) {
	o.InstanceDisplayText = &v
}

// GetInstanceLabel returns the InstanceLabel field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetInstanceLabel() string {
	if o == nil || IsNil(o.InstanceLabel) {
		var ret string
		return ret
	}
	return *o.InstanceLabel
}

// GetInstanceLabelOk returns a tuple with the InstanceLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetInstanceLabelOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceLabel) {
		return nil, false
	}
	return o.InstanceLabel, true
}

// HasInstanceLabel returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasInstanceLabel() bool {
	if o != nil && !IsNil(o.InstanceLabel) {
		return true
	}

	return false
}

// SetInstanceLabel gets a reference to the given string and assigns it to the InstanceLabel field.
func (o *UpdateNavigatorRequest) SetInstanceLabel(v string) {
	o.InstanceLabel = &v
}

// GetListColumns returns the ListColumns field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetListColumns() []ListColumn {
	if o == nil || IsNil(o.ListColumns) {
		var ret []ListColumn
		return ret
	}
	return o.ListColumns
}

// GetListColumnsOk returns a tuple with the ListColumns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetListColumnsOk() ([]ListColumn, bool) {
	if o == nil || IsNil(o.ListColumns) {
		return nil, false
	}
	return o.ListColumns, true
}

// HasListColumns returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasListColumns() bool {
	if o != nil && !IsNil(o.ListColumns) {
		return true
	}

	return false
}

// SetListColumns gets a reference to the given []ListColumn and assigns it to the ListColumns field.
func (o *UpdateNavigatorRequest) SetListColumns(v []ListColumn) {
	o.ListColumns = v
}

// GetPropertyIdentifierTemplate returns the PropertyIdentifierTemplate field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetPropertyIdentifierTemplate() string {
	if o == nil || IsNil(o.PropertyIdentifierTemplate) {
		var ret string
		return ret
	}
	return *o.PropertyIdentifierTemplate
}

// GetPropertyIdentifierTemplateOk returns a tuple with the PropertyIdentifierTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetPropertyIdentifierTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.PropertyIdentifierTemplate) {
		return nil, false
	}
	return o.PropertyIdentifierTemplate, true
}

// HasPropertyIdentifierTemplate returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasPropertyIdentifierTemplate() bool {
	if o != nil && !IsNil(o.PropertyIdentifierTemplate) {
		return true
	}

	return false
}

// SetPropertyIdentifierTemplate gets a reference to the given string and assigns it to the PropertyIdentifierTemplate field.
func (o *UpdateNavigatorRequest) SetPropertyIdentifierTemplate(v string) {
	o.PropertyIdentifierTemplate = &v
}

// GetRequiredProperties returns the RequiredProperties field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetRequiredProperties() []string {
	if o == nil || IsNil(o.RequiredProperties) {
		var ret []string
		return ret
	}
	return o.RequiredProperties
}

// GetRequiredPropertiesOk returns a tuple with the RequiredProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetRequiredPropertiesOk() ([]string, bool) {
	if o == nil || IsNil(o.RequiredProperties) {
		return nil, false
	}
	return o.RequiredProperties, true
}

// HasRequiredProperties returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasRequiredProperties() bool {
	if o != nil && !IsNil(o.RequiredProperties) {
		return true
	}

	return false
}

// SetRequiredProperties gets a reference to the given []string and assigns it to the RequiredProperties field.
func (o *UpdateNavigatorRequest) SetRequiredProperties(v []string) {
	o.RequiredProperties = v
}

// GetSystemTypes returns the SystemTypes field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetSystemTypes() []string {
	if o == nil || IsNil(o.SystemTypes) {
		var ret []string
		return ret
	}
	return o.SystemTypes
}

// GetSystemTypesOk returns a tuple with the SystemTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetSystemTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.SystemTypes) {
		return nil, false
	}
	return o.SystemTypes, true
}

// HasSystemTypes returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasSystemTypes() bool {
	if o != nil && !IsNil(o.SystemTypes) {
		return true
	}

	return false
}

// SetSystemTypes gets a reference to the given []string and assigns it to the SystemTypes field.
func (o *UpdateNavigatorRequest) SetSystemTypes(v []string) {
	o.SystemTypes = v
}

// GetSummaryMetricLabel returns the SummaryMetricLabel field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetSummaryMetricLabel() string {
	if o == nil || IsNil(o.SummaryMetricLabel) {
		var ret string
		return ret
	}
	return *o.SummaryMetricLabel
}

// GetSummaryMetricLabelOk returns a tuple with the SummaryMetricLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetSummaryMetricLabelOk() (*string, bool) {
	if o == nil || IsNil(o.SummaryMetricLabel) {
		return nil, false
	}
	return o.SummaryMetricLabel, true
}

// HasSummaryMetricLabel returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasSummaryMetricLabel() bool {
	if o != nil && !IsNil(o.SummaryMetricLabel) {
		return true
	}

	return false
}

// SetSummaryMetricLabel gets a reference to the given string and assigns it to the SummaryMetricLabel field.
func (o *UpdateNavigatorRequest) SetSummaryMetricLabel(v string) {
	o.SummaryMetricLabel = &v
}

// GetSummaryMetricProgramText returns the SummaryMetricProgramText field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetSummaryMetricProgramText() string {
	if o == nil || IsNil(o.SummaryMetricProgramText) {
		var ret string
		return ret
	}
	return *o.SummaryMetricProgramText
}

// GetSummaryMetricProgramTextOk returns a tuple with the SummaryMetricProgramText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetSummaryMetricProgramTextOk() (*string, bool) {
	if o == nil || IsNil(o.SummaryMetricProgramText) {
		return nil, false
	}
	return o.SummaryMetricProgramText, true
}

// HasSummaryMetricProgramText returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasSummaryMetricProgramText() bool {
	if o != nil && !IsNil(o.SummaryMetricProgramText) {
		return true
	}

	return false
}

// SetSummaryMetricProgramText gets a reference to the given string and assigns it to the SummaryMetricProgramText field.
func (o *UpdateNavigatorRequest) SetSummaryMetricProgramText(v string) {
	o.SummaryMetricProgramText = &v
}

// GetTooltipKeyList returns the TooltipKeyList field value if set, zero value otherwise.
func (o *UpdateNavigatorRequest) GetTooltipKeyList() []TooltipKey {
	if o == nil || IsNil(o.TooltipKeyList) {
		var ret []TooltipKey
		return ret
	}
	return o.TooltipKeyList
}

// GetTooltipKeyListOk returns a tuple with the TooltipKeyList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNavigatorRequest) GetTooltipKeyListOk() ([]TooltipKey, bool) {
	if o == nil || IsNil(o.TooltipKeyList) {
		return nil, false
	}
	return o.TooltipKeyList, true
}

// HasTooltipKeyList returns a boolean if a field has been set.
func (o *UpdateNavigatorRequest) HasTooltipKeyList() bool {
	if o != nil && !IsNil(o.TooltipKeyList) {
		return true
	}

	return false
}

// SetTooltipKeyList gets a reference to the given []TooltipKey and assigns it to the TooltipKeyList field.
func (o *UpdateNavigatorRequest) SetTooltipKeyList(v []TooltipKey) {
	o.TooltipKeyList = v
}

func (o UpdateNavigatorRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNavigatorRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AlertQuery) {
		toSerialize["alertQuery"] = o.AlertQuery
	}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.DefaultGroupBy) {
		toSerialize["defaultGroupBy"] = o.DefaultGroupBy
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.EntityMetrics) {
		toSerialize["entityMetrics"] = o.EntityMetrics
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IdDisplayName) {
		toSerialize["idDisplayName"] = o.IdDisplayName
	}
	if !IsNil(o.InstanceDashboards) {
		toSerialize["instanceDashboards"] = o.InstanceDashboards
	}
	if !IsNil(o.InstanceDisplayText) {
		toSerialize["instanceDisplayText"] = o.InstanceDisplayText
	}
	if !IsNil(o.InstanceLabel) {
		toSerialize["instanceLabel"] = o.InstanceLabel
	}
	if !IsNil(o.ListColumns) {
		toSerialize["listColumns"] = o.ListColumns
	}
	if !IsNil(o.PropertyIdentifierTemplate) {
		toSerialize["propertyIdentifierTemplate"] = o.PropertyIdentifierTemplate
	}
	if !IsNil(o.RequiredProperties) {
		toSerialize["requiredProperties"] = o.RequiredProperties
	}
	if !IsNil(o.SystemTypes) {
		toSerialize["systemTypes"] = o.SystemTypes
	}
	if !IsNil(o.SummaryMetricLabel) {
		toSerialize["summaryMetricLabel"] = o.SummaryMetricLabel
	}
	if !IsNil(o.SummaryMetricProgramText) {
		toSerialize["summaryMetricProgramText"] = o.SummaryMetricProgramText
	}
	if !IsNil(o.TooltipKeyList) {
		toSerialize["tooltipKeyList"] = o.TooltipKeyList
	}
	return toSerialize, nil
}

type NullableUpdateNavigatorRequest struct {
	value *UpdateNavigatorRequest
	isSet bool
}

func (v NullableUpdateNavigatorRequest) Get() *UpdateNavigatorRequest {
	return v.value
}

func (v *NullableUpdateNavigatorRequest) Set(val *UpdateNavigatorRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNavigatorRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNavigatorRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNavigatorRequest(val *UpdateNavigatorRequest) *NullableUpdateNavigatorRequest {
	return &NullableUpdateNavigatorRequest{value: val, isSet: true}
}

func (v NullableUpdateNavigatorRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNavigatorRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


