/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the DisplayOptionsForTheChartLegend type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisplayOptionsForTheChartLegend{}

// DisplayOptionsForTheChartLegend Controls the display of a legend and the dimensions to show in it 
type DisplayOptionsForTheChartLegend struct {
	// The dimension to show in the legend 
	DimensionInLegend *string `json:"dimensionInLegend,omitempty"`
	// Controls the display of a chart legend 
	ShowLegend *bool `json:"showLegend,omitempty"`
}

// NewDisplayOptionsForTheChartLegend instantiates a new DisplayOptionsForTheChartLegend object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisplayOptionsForTheChartLegend() *DisplayOptionsForTheChartLegend {
	this := DisplayOptionsForTheChartLegend{}
	var showLegend bool = false
	this.ShowLegend = &showLegend
	return &this
}

// NewDisplayOptionsForTheChartLegendWithDefaults instantiates a new DisplayOptionsForTheChartLegend object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisplayOptionsForTheChartLegendWithDefaults() *DisplayOptionsForTheChartLegend {
	this := DisplayOptionsForTheChartLegend{}
	var showLegend bool = false
	this.ShowLegend = &showLegend
	return &this
}

// GetDimensionInLegend returns the DimensionInLegend field value if set, zero value otherwise.
func (o *DisplayOptionsForTheChartLegend) GetDimensionInLegend() string {
	if o == nil || IsNil(o.DimensionInLegend) {
		var ret string
		return ret
	}
	return *o.DimensionInLegend
}

// GetDimensionInLegendOk returns a tuple with the DimensionInLegend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayOptionsForTheChartLegend) GetDimensionInLegendOk() (*string, bool) {
	if o == nil || IsNil(o.DimensionInLegend) {
		return nil, false
	}
	return o.DimensionInLegend, true
}

// HasDimensionInLegend returns a boolean if a field has been set.
func (o *DisplayOptionsForTheChartLegend) HasDimensionInLegend() bool {
	if o != nil && !IsNil(o.DimensionInLegend) {
		return true
	}

	return false
}

// SetDimensionInLegend gets a reference to the given string and assigns it to the DimensionInLegend field.
func (o *DisplayOptionsForTheChartLegend) SetDimensionInLegend(v string) {
	o.DimensionInLegend = &v
}

// GetShowLegend returns the ShowLegend field value if set, zero value otherwise.
func (o *DisplayOptionsForTheChartLegend) GetShowLegend() bool {
	if o == nil || IsNil(o.ShowLegend) {
		var ret bool
		return ret
	}
	return *o.ShowLegend
}

// GetShowLegendOk returns a tuple with the ShowLegend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayOptionsForTheChartLegend) GetShowLegendOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowLegend) {
		return nil, false
	}
	return o.ShowLegend, true
}

// HasShowLegend returns a boolean if a field has been set.
func (o *DisplayOptionsForTheChartLegend) HasShowLegend() bool {
	if o != nil && !IsNil(o.ShowLegend) {
		return true
	}

	return false
}

// SetShowLegend gets a reference to the given bool and assigns it to the ShowLegend field.
func (o *DisplayOptionsForTheChartLegend) SetShowLegend(v bool) {
	o.ShowLegend = &v
}

func (o DisplayOptionsForTheChartLegend) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisplayOptionsForTheChartLegend) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DimensionInLegend) {
		toSerialize["dimensionInLegend"] = o.DimensionInLegend
	}
	if !IsNil(o.ShowLegend) {
		toSerialize["showLegend"] = o.ShowLegend
	}
	return toSerialize, nil
}

type NullableDisplayOptionsForTheChartLegend struct {
	value *DisplayOptionsForTheChartLegend
	isSet bool
}

func (v NullableDisplayOptionsForTheChartLegend) Get() *DisplayOptionsForTheChartLegend {
	return v.value
}

func (v *NullableDisplayOptionsForTheChartLegend) Set(val *DisplayOptionsForTheChartLegend) {
	v.value = val
	v.isSet = true
}

func (v NullableDisplayOptionsForTheChartLegend) IsSet() bool {
	return v.isSet
}

func (v *NullableDisplayOptionsForTheChartLegend) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisplayOptionsForTheChartLegend(val *DisplayOptionsForTheChartLegend) *NullableDisplayOptionsForTheChartLegend {
	return &NullableDisplayOptionsForTheChartLegend{value: val, isSet: true}
}

func (v NullableDisplayOptionsForTheChartLegend) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisplayOptionsForTheChartLegend) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


