/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the ChartOptionsHistogramChartOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChartOptionsHistogramChartOptions{}

// ChartOptionsHistogramChartOptions struct for ChartOptionsHistogramChartOptions
type ChartOptionsHistogramChartOptions struct {
	// Color palette index for histogram color theme 
	ColorThemeIndex *int32 `json:"colorThemeIndex,omitempty"`
}

// NewChartOptionsHistogramChartOptions instantiates a new ChartOptionsHistogramChartOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChartOptionsHistogramChartOptions() *ChartOptionsHistogramChartOptions {
	this := ChartOptionsHistogramChartOptions{}
	var colorThemeIndex int32 = 15
	this.ColorThemeIndex = &colorThemeIndex
	return &this
}

// NewChartOptionsHistogramChartOptionsWithDefaults instantiates a new ChartOptionsHistogramChartOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartOptionsHistogramChartOptionsWithDefaults() *ChartOptionsHistogramChartOptions {
	this := ChartOptionsHistogramChartOptions{}
	var colorThemeIndex int32 = 15
	this.ColorThemeIndex = &colorThemeIndex
	return &this
}

// GetColorThemeIndex returns the ColorThemeIndex field value if set, zero value otherwise.
func (o *ChartOptionsHistogramChartOptions) GetColorThemeIndex() int32 {
	if o == nil || IsNil(o.ColorThemeIndex) {
		var ret int32
		return ret
	}
	return *o.ColorThemeIndex
}

// GetColorThemeIndexOk returns a tuple with the ColorThemeIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartOptionsHistogramChartOptions) GetColorThemeIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.ColorThemeIndex) {
		return nil, false
	}
	return o.ColorThemeIndex, true
}

// HasColorThemeIndex returns a boolean if a field has been set.
func (o *ChartOptionsHistogramChartOptions) HasColorThemeIndex() bool {
	if o != nil && !IsNil(o.ColorThemeIndex) {
		return true
	}

	return false
}

// SetColorThemeIndex gets a reference to the given int32 and assigns it to the ColorThemeIndex field.
func (o *ChartOptionsHistogramChartOptions) SetColorThemeIndex(v int32) {
	o.ColorThemeIndex = &v
}

func (o ChartOptionsHistogramChartOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChartOptionsHistogramChartOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ColorThemeIndex) {
		toSerialize["colorThemeIndex"] = o.ColorThemeIndex
	}
	return toSerialize, nil
}

type NullableChartOptionsHistogramChartOptions struct {
	value *ChartOptionsHistogramChartOptions
	isSet bool
}

func (v NullableChartOptionsHistogramChartOptions) Get() *ChartOptionsHistogramChartOptions {
	return v.value
}

func (v *NullableChartOptionsHistogramChartOptions) Set(val *ChartOptionsHistogramChartOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableChartOptionsHistogramChartOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableChartOptionsHistogramChartOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChartOptionsHistogramChartOptions(val *ChartOptionsHistogramChartOptions) *NullableChartOptionsHistogramChartOptions {
	return &NullableChartOptionsHistogramChartOptions{value: val, isSet: true}
}

func (v NullableChartOptionsHistogramChartOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChartOptionsHistogramChartOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


