/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the SimpleDashboardRequestBodyChartObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SimpleDashboardRequestBodyChartObject{}

// SimpleDashboardRequestBodyChartObject Simple dashboard request chart object 
type SimpleDashboardRequestBodyChartObject struct {
	// Metadata object 
	CustomProperties map[string]interface{} `json:"customProperties,omitempty"`
	// Chart description 
	Description *string `json:"description,omitempty"`
	// ID of an existing chart 
	ChartId interface{} `json:"chartId,omitempty"`
	// Chart name 
	Name *string `json:"name,omitempty"`
	Options *ChartOptions `json:"options,omitempty"`
	// For internal use only. 
	PackageSpecifications *string `json:"packageSpecifications,omitempty"`
	// SignalFlow program for chart data 
	ProgramText *string `json:"programText,omitempty"`
	// Tags for chart 
	Tags []string `json:"tags,omitempty"`
}

// NewSimpleDashboardRequestBodyChartObject instantiates a new SimpleDashboardRequestBodyChartObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSimpleDashboardRequestBodyChartObject() *SimpleDashboardRequestBodyChartObject {
	this := SimpleDashboardRequestBodyChartObject{}
	return &this
}

// NewSimpleDashboardRequestBodyChartObjectWithDefaults instantiates a new SimpleDashboardRequestBodyChartObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSimpleDashboardRequestBodyChartObjectWithDefaults() *SimpleDashboardRequestBodyChartObject {
	this := SimpleDashboardRequestBodyChartObject{}
	return &this
}

// GetCustomProperties returns the CustomProperties field value if set, zero value otherwise.
func (o *SimpleDashboardRequestBodyChartObject) GetCustomProperties() map[string]interface{} {
	if o == nil || IsNil(o.CustomProperties) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomProperties
}

// GetCustomPropertiesOk returns a tuple with the CustomProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimpleDashboardRequestBodyChartObject) GetCustomPropertiesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomProperties) {
		return map[string]interface{}{}, false
	}
	return o.CustomProperties, true
}

// HasCustomProperties returns a boolean if a field has been set.
func (o *SimpleDashboardRequestBodyChartObject) HasCustomProperties() bool {
	if o != nil && !IsNil(o.CustomProperties) {
		return true
	}

	return false
}

// SetCustomProperties gets a reference to the given map[string]interface{} and assigns it to the CustomProperties field.
func (o *SimpleDashboardRequestBodyChartObject) SetCustomProperties(v map[string]interface{}) {
	o.CustomProperties = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SimpleDashboardRequestBodyChartObject) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimpleDashboardRequestBodyChartObject) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SimpleDashboardRequestBodyChartObject) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SimpleDashboardRequestBodyChartObject) SetDescription(v string) {
	o.Description = &v
}

// GetChartId returns the ChartId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SimpleDashboardRequestBodyChartObject) GetChartId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ChartId
}

// GetChartIdOk returns a tuple with the ChartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SimpleDashboardRequestBodyChartObject) GetChartIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ChartId) {
		return nil, false
	}
	return &o.ChartId, true
}

// HasChartId returns a boolean if a field has been set.
func (o *SimpleDashboardRequestBodyChartObject) HasChartId() bool {
	if o != nil && !IsNil(o.ChartId) {
		return true
	}

	return false
}

// SetChartId gets a reference to the given interface{} and assigns it to the ChartId field.
func (o *SimpleDashboardRequestBodyChartObject) SetChartId(v interface{}) {
	o.ChartId = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SimpleDashboardRequestBodyChartObject) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimpleDashboardRequestBodyChartObject) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SimpleDashboardRequestBodyChartObject) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SimpleDashboardRequestBodyChartObject) SetName(v string) {
	o.Name = &v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *SimpleDashboardRequestBodyChartObject) GetOptions() ChartOptions {
	if o == nil || IsNil(o.Options) {
		var ret ChartOptions
		return ret
	}
	return *o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimpleDashboardRequestBodyChartObject) GetOptionsOk() (*ChartOptions, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *SimpleDashboardRequestBodyChartObject) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given ChartOptions and assigns it to the Options field.
func (o *SimpleDashboardRequestBodyChartObject) SetOptions(v ChartOptions) {
	o.Options = &v
}

// GetPackageSpecifications returns the PackageSpecifications field value if set, zero value otherwise.
func (o *SimpleDashboardRequestBodyChartObject) GetPackageSpecifications() string {
	if o == nil || IsNil(o.PackageSpecifications) {
		var ret string
		return ret
	}
	return *o.PackageSpecifications
}

// GetPackageSpecificationsOk returns a tuple with the PackageSpecifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimpleDashboardRequestBodyChartObject) GetPackageSpecificationsOk() (*string, bool) {
	if o == nil || IsNil(o.PackageSpecifications) {
		return nil, false
	}
	return o.PackageSpecifications, true
}

// HasPackageSpecifications returns a boolean if a field has been set.
func (o *SimpleDashboardRequestBodyChartObject) HasPackageSpecifications() bool {
	if o != nil && !IsNil(o.PackageSpecifications) {
		return true
	}

	return false
}

// SetPackageSpecifications gets a reference to the given string and assigns it to the PackageSpecifications field.
func (o *SimpleDashboardRequestBodyChartObject) SetPackageSpecifications(v string) {
	o.PackageSpecifications = &v
}

// GetProgramText returns the ProgramText field value if set, zero value otherwise.
func (o *SimpleDashboardRequestBodyChartObject) GetProgramText() string {
	if o == nil || IsNil(o.ProgramText) {
		var ret string
		return ret
	}
	return *o.ProgramText
}

// GetProgramTextOk returns a tuple with the ProgramText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimpleDashboardRequestBodyChartObject) GetProgramTextOk() (*string, bool) {
	if o == nil || IsNil(o.ProgramText) {
		return nil, false
	}
	return o.ProgramText, true
}

// HasProgramText returns a boolean if a field has been set.
func (o *SimpleDashboardRequestBodyChartObject) HasProgramText() bool {
	if o != nil && !IsNil(o.ProgramText) {
		return true
	}

	return false
}

// SetProgramText gets a reference to the given string and assigns it to the ProgramText field.
func (o *SimpleDashboardRequestBodyChartObject) SetProgramText(v string) {
	o.ProgramText = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SimpleDashboardRequestBodyChartObject) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimpleDashboardRequestBodyChartObject) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SimpleDashboardRequestBodyChartObject) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *SimpleDashboardRequestBodyChartObject) SetTags(v []string) {
	o.Tags = v
}

func (o SimpleDashboardRequestBodyChartObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SimpleDashboardRequestBodyChartObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomProperties) {
		toSerialize["customProperties"] = o.CustomProperties
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.ChartId != nil {
		toSerialize["chartId"] = o.ChartId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	if !IsNil(o.PackageSpecifications) {
		toSerialize["packageSpecifications"] = o.PackageSpecifications
	}
	if !IsNil(o.ProgramText) {
		toSerialize["programText"] = o.ProgramText
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullableSimpleDashboardRequestBodyChartObject struct {
	value *SimpleDashboardRequestBodyChartObject
	isSet bool
}

func (v NullableSimpleDashboardRequestBodyChartObject) Get() *SimpleDashboardRequestBodyChartObject {
	return v.value
}

func (v *NullableSimpleDashboardRequestBodyChartObject) Set(val *SimpleDashboardRequestBodyChartObject) {
	v.value = val
	v.isSet = true
}

func (v NullableSimpleDashboardRequestBodyChartObject) IsSet() bool {
	return v.isSet
}

func (v *NullableSimpleDashboardRequestBodyChartObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSimpleDashboardRequestBodyChartObject(val *SimpleDashboardRequestBodyChartObject) *NullableSimpleDashboardRequestBodyChartObject {
	return &NullableSimpleDashboardRequestBodyChartObject{value: val, isSet: true}
}

func (v NullableSimpleDashboardRequestBodyChartObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSimpleDashboardRequestBodyChartObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


