/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChartPublishLabelOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChartPublishLabelOptions{}

// ChartPublishLabelOptions Plot options 
type ChartPublishLabelOptions struct {
	// Alternate plot name, displayed in Data Table 
	DisplayName *string `json:"displayName,omitempty"`
	// Label of `publish()` object for this plot 
	Label string `json:"label"`
	// Plot color palette index 
	PaletteIndex *int32 `json:"paletteIndex,omitempty"`
	// Visualization override for this plot 
	PlotType *string `json:"plotType,omitempty"`
	// String prepended to values 
	ValuePrefix *string `json:"valuePrefix,omitempty"`
	// String appended to values 
	ValueSuffix *string `json:"valueSuffix,omitempty"`
	// Unit of measure for values 
	ValueUnit *string `json:"valueUnit,omitempty"`
	// Y-axis position in plot 
	YAxis *int32 `json:"yAxis,omitempty"`
}

type _ChartPublishLabelOptions ChartPublishLabelOptions

// NewChartPublishLabelOptions instantiates a new ChartPublishLabelOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChartPublishLabelOptions(label string) *ChartPublishLabelOptions {
	this := ChartPublishLabelOptions{}
	this.Label = label
	var yAxis int32 = 0
	this.YAxis = &yAxis
	return &this
}

// NewChartPublishLabelOptionsWithDefaults instantiates a new ChartPublishLabelOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartPublishLabelOptionsWithDefaults() *ChartPublishLabelOptions {
	this := ChartPublishLabelOptions{}
	var yAxis int32 = 0
	this.YAxis = &yAxis
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ChartPublishLabelOptions) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartPublishLabelOptions) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ChartPublishLabelOptions) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ChartPublishLabelOptions) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetLabel returns the Label field value
func (o *ChartPublishLabelOptions) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ChartPublishLabelOptions) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ChartPublishLabelOptions) SetLabel(v string) {
	o.Label = v
}

// GetPaletteIndex returns the PaletteIndex field value if set, zero value otherwise.
func (o *ChartPublishLabelOptions) GetPaletteIndex() int32 {
	if o == nil || IsNil(o.PaletteIndex) {
		var ret int32
		return ret
	}
	return *o.PaletteIndex
}

// GetPaletteIndexOk returns a tuple with the PaletteIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartPublishLabelOptions) GetPaletteIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.PaletteIndex) {
		return nil, false
	}
	return o.PaletteIndex, true
}

// HasPaletteIndex returns a boolean if a field has been set.
func (o *ChartPublishLabelOptions) HasPaletteIndex() bool {
	if o != nil && !IsNil(o.PaletteIndex) {
		return true
	}

	return false
}

// SetPaletteIndex gets a reference to the given int32 and assigns it to the PaletteIndex field.
func (o *ChartPublishLabelOptions) SetPaletteIndex(v int32) {
	o.PaletteIndex = &v
}

// GetPlotType returns the PlotType field value if set, zero value otherwise.
func (o *ChartPublishLabelOptions) GetPlotType() string {
	if o == nil || IsNil(o.PlotType) {
		var ret string
		return ret
	}
	return *o.PlotType
}

// GetPlotTypeOk returns a tuple with the PlotType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartPublishLabelOptions) GetPlotTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PlotType) {
		return nil, false
	}
	return o.PlotType, true
}

// HasPlotType returns a boolean if a field has been set.
func (o *ChartPublishLabelOptions) HasPlotType() bool {
	if o != nil && !IsNil(o.PlotType) {
		return true
	}

	return false
}

// SetPlotType gets a reference to the given string and assigns it to the PlotType field.
func (o *ChartPublishLabelOptions) SetPlotType(v string) {
	o.PlotType = &v
}

// GetValuePrefix returns the ValuePrefix field value if set, zero value otherwise.
func (o *ChartPublishLabelOptions) GetValuePrefix() string {
	if o == nil || IsNil(o.ValuePrefix) {
		var ret string
		return ret
	}
	return *o.ValuePrefix
}

// GetValuePrefixOk returns a tuple with the ValuePrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartPublishLabelOptions) GetValuePrefixOk() (*string, bool) {
	if o == nil || IsNil(o.ValuePrefix) {
		return nil, false
	}
	return o.ValuePrefix, true
}

// HasValuePrefix returns a boolean if a field has been set.
func (o *ChartPublishLabelOptions) HasValuePrefix() bool {
	if o != nil && !IsNil(o.ValuePrefix) {
		return true
	}

	return false
}

// SetValuePrefix gets a reference to the given string and assigns it to the ValuePrefix field.
func (o *ChartPublishLabelOptions) SetValuePrefix(v string) {
	o.ValuePrefix = &v
}

// GetValueSuffix returns the ValueSuffix field value if set, zero value otherwise.
func (o *ChartPublishLabelOptions) GetValueSuffix() string {
	if o == nil || IsNil(o.ValueSuffix) {
		var ret string
		return ret
	}
	return *o.ValueSuffix
}

// GetValueSuffixOk returns a tuple with the ValueSuffix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartPublishLabelOptions) GetValueSuffixOk() (*string, bool) {
	if o == nil || IsNil(o.ValueSuffix) {
		return nil, false
	}
	return o.ValueSuffix, true
}

// HasValueSuffix returns a boolean if a field has been set.
func (o *ChartPublishLabelOptions) HasValueSuffix() bool {
	if o != nil && !IsNil(o.ValueSuffix) {
		return true
	}

	return false
}

// SetValueSuffix gets a reference to the given string and assigns it to the ValueSuffix field.
func (o *ChartPublishLabelOptions) SetValueSuffix(v string) {
	o.ValueSuffix = &v
}

// GetValueUnit returns the ValueUnit field value if set, zero value otherwise.
func (o *ChartPublishLabelOptions) GetValueUnit() string {
	if o == nil || IsNil(o.ValueUnit) {
		var ret string
		return ret
	}
	return *o.ValueUnit
}

// GetValueUnitOk returns a tuple with the ValueUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartPublishLabelOptions) GetValueUnitOk() (*string, bool) {
	if o == nil || IsNil(o.ValueUnit) {
		return nil, false
	}
	return o.ValueUnit, true
}

// HasValueUnit returns a boolean if a field has been set.
func (o *ChartPublishLabelOptions) HasValueUnit() bool {
	if o != nil && !IsNil(o.ValueUnit) {
		return true
	}

	return false
}

// SetValueUnit gets a reference to the given string and assigns it to the ValueUnit field.
func (o *ChartPublishLabelOptions) SetValueUnit(v string) {
	o.ValueUnit = &v
}

// GetYAxis returns the YAxis field value if set, zero value otherwise.
func (o *ChartPublishLabelOptions) GetYAxis() int32 {
	if o == nil || IsNil(o.YAxis) {
		var ret int32
		return ret
	}
	return *o.YAxis
}

// GetYAxisOk returns a tuple with the YAxis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartPublishLabelOptions) GetYAxisOk() (*int32, bool) {
	if o == nil || IsNil(o.YAxis) {
		return nil, false
	}
	return o.YAxis, true
}

// HasYAxis returns a boolean if a field has been set.
func (o *ChartPublishLabelOptions) HasYAxis() bool {
	if o != nil && !IsNil(o.YAxis) {
		return true
	}

	return false
}

// SetYAxis gets a reference to the given int32 and assigns it to the YAxis field.
func (o *ChartPublishLabelOptions) SetYAxis(v int32) {
	o.YAxis = &v
}

func (o ChartPublishLabelOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChartPublishLabelOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	toSerialize["label"] = o.Label
	if !IsNil(o.PaletteIndex) {
		toSerialize["paletteIndex"] = o.PaletteIndex
	}
	if !IsNil(o.PlotType) {
		toSerialize["plotType"] = o.PlotType
	}
	if !IsNil(o.ValuePrefix) {
		toSerialize["valuePrefix"] = o.ValuePrefix
	}
	if !IsNil(o.ValueSuffix) {
		toSerialize["valueSuffix"] = o.ValueSuffix
	}
	if !IsNil(o.ValueUnit) {
		toSerialize["valueUnit"] = o.ValueUnit
	}
	if !IsNil(o.YAxis) {
		toSerialize["yAxis"] = o.YAxis
	}
	return toSerialize, nil
}

func (o *ChartPublishLabelOptions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChartPublishLabelOptions := _ChartPublishLabelOptions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChartPublishLabelOptions)

	if err != nil {
		return err
	}

	*o = ChartPublishLabelOptions(varChartPublishLabelOptions)

	return err
}

type NullableChartPublishLabelOptions struct {
	value *ChartPublishLabelOptions
	isSet bool
}

func (v NullableChartPublishLabelOptions) Get() *ChartPublishLabelOptions {
	return v.value
}

func (v *NullableChartPublishLabelOptions) Set(val *ChartPublishLabelOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableChartPublishLabelOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableChartPublishLabelOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChartPublishLabelOptions(val *ChartPublishLabelOptions) *NullableChartPublishLabelOptions {
	return &NullableChartPublishLabelOptions{value: val, isSet: true}
}

func (v NullableChartPublishLabelOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChartPublishLabelOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


