/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the PropertiesForAreaCharts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PropertiesForAreaCharts{}

// PropertiesForAreaCharts struct for PropertiesForAreaCharts
type PropertiesForAreaCharts struct {
	// Controls appearance of markers for data arrival times 
	ShowDataMarkers *bool `json:"showDataMarkers,omitempty"`
}

// NewPropertiesForAreaCharts instantiates a new PropertiesForAreaCharts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPropertiesForAreaCharts() *PropertiesForAreaCharts {
	this := PropertiesForAreaCharts{}
	var showDataMarkers bool = false
	this.ShowDataMarkers = &showDataMarkers
	return &this
}

// NewPropertiesForAreaChartsWithDefaults instantiates a new PropertiesForAreaCharts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPropertiesForAreaChartsWithDefaults() *PropertiesForAreaCharts {
	this := PropertiesForAreaCharts{}
	var showDataMarkers bool = false
	this.ShowDataMarkers = &showDataMarkers
	return &this
}

// GetShowDataMarkers returns the ShowDataMarkers field value if set, zero value otherwise.
func (o *PropertiesForAreaCharts) GetShowDataMarkers() bool {
	if o == nil || IsNil(o.ShowDataMarkers) {
		var ret bool
		return ret
	}
	return *o.ShowDataMarkers
}

// GetShowDataMarkersOk returns a tuple with the ShowDataMarkers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertiesForAreaCharts) GetShowDataMarkersOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowDataMarkers) {
		return nil, false
	}
	return o.ShowDataMarkers, true
}

// HasShowDataMarkers returns a boolean if a field has been set.
func (o *PropertiesForAreaCharts) HasShowDataMarkers() bool {
	if o != nil && !IsNil(o.ShowDataMarkers) {
		return true
	}

	return false
}

// SetShowDataMarkers gets a reference to the given bool and assigns it to the ShowDataMarkers field.
func (o *PropertiesForAreaCharts) SetShowDataMarkers(v bool) {
	o.ShowDataMarkers = &v
}

func (o PropertiesForAreaCharts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PropertiesForAreaCharts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ShowDataMarkers) {
		toSerialize["showDataMarkers"] = o.ShowDataMarkers
	}
	return toSerialize, nil
}

type NullablePropertiesForAreaCharts struct {
	value *PropertiesForAreaCharts
	isSet bool
}

func (v NullablePropertiesForAreaCharts) Get() *PropertiesForAreaCharts {
	return v.value
}

func (v *NullablePropertiesForAreaCharts) Set(val *PropertiesForAreaCharts) {
	v.value = val
	v.isSet = true
}

func (v NullablePropertiesForAreaCharts) IsSet() bool {
	return v.isSet
}

func (v *NullablePropertiesForAreaCharts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePropertiesForAreaCharts(val *PropertiesForAreaCharts) *NullablePropertiesForAreaCharts {
	return &NullablePropertiesForAreaCharts{value: val, isSet: true}
}

func (v NullablePropertiesForAreaCharts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePropertiesForAreaCharts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


