/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the SpecifiesColorRangeOptionsForColoringAHeatmapChart type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpecifiesColorRangeOptionsForColoringAHeatmapChart{}

// SpecifiesColorRangeOptionsForColoringAHeatmapChart Heatmap color range options 
type SpecifiesColorRangeOptionsForColoringAHeatmapChart struct {
	// Heatmap starting color 
	Color *string `json:"color,omitempty"`
	// Color of largest data value 
	Max *string `json:"max,omitempty"`
	// Color of smallest data value 
	Min *string `json:"min,omitempty"`
}

// NewSpecifiesColorRangeOptionsForColoringAHeatmapChart instantiates a new SpecifiesColorRangeOptionsForColoringAHeatmapChart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpecifiesColorRangeOptionsForColoringAHeatmapChart() *SpecifiesColorRangeOptionsForColoringAHeatmapChart {
	this := SpecifiesColorRangeOptionsForColoringAHeatmapChart{}
	return &this
}

// NewSpecifiesColorRangeOptionsForColoringAHeatmapChartWithDefaults instantiates a new SpecifiesColorRangeOptionsForColoringAHeatmapChart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpecifiesColorRangeOptionsForColoringAHeatmapChartWithDefaults() *SpecifiesColorRangeOptionsForColoringAHeatmapChart {
	this := SpecifiesColorRangeOptionsForColoringAHeatmapChart{}
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *SpecifiesColorRangeOptionsForColoringAHeatmapChart) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpecifiesColorRangeOptionsForColoringAHeatmapChart) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *SpecifiesColorRangeOptionsForColoringAHeatmapChart) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *SpecifiesColorRangeOptionsForColoringAHeatmapChart) SetColor(v string) {
	o.Color = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *SpecifiesColorRangeOptionsForColoringAHeatmapChart) GetMax() string {
	if o == nil || IsNil(o.Max) {
		var ret string
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpecifiesColorRangeOptionsForColoringAHeatmapChart) GetMaxOk() (*string, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *SpecifiesColorRangeOptionsForColoringAHeatmapChart) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given string and assigns it to the Max field.
func (o *SpecifiesColorRangeOptionsForColoringAHeatmapChart) SetMax(v string) {
	o.Max = &v
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *SpecifiesColorRangeOptionsForColoringAHeatmapChart) GetMin() string {
	if o == nil || IsNil(o.Min) {
		var ret string
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpecifiesColorRangeOptionsForColoringAHeatmapChart) GetMinOk() (*string, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *SpecifiesColorRangeOptionsForColoringAHeatmapChart) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given string and assigns it to the Min field.
func (o *SpecifiesColorRangeOptionsForColoringAHeatmapChart) SetMin(v string) {
	o.Min = &v
}

func (o SpecifiesColorRangeOptionsForColoringAHeatmapChart) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpecifiesColorRangeOptionsForColoringAHeatmapChart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	if !IsNil(o.Min) {
		toSerialize["min"] = o.Min
	}
	return toSerialize, nil
}

type NullableSpecifiesColorRangeOptionsForColoringAHeatmapChart struct {
	value *SpecifiesColorRangeOptionsForColoringAHeatmapChart
	isSet bool
}

func (v NullableSpecifiesColorRangeOptionsForColoringAHeatmapChart) Get() *SpecifiesColorRangeOptionsForColoringAHeatmapChart {
	return v.value
}

func (v *NullableSpecifiesColorRangeOptionsForColoringAHeatmapChart) Set(val *SpecifiesColorRangeOptionsForColoringAHeatmapChart) {
	v.value = val
	v.isSet = true
}

func (v NullableSpecifiesColorRangeOptionsForColoringAHeatmapChart) IsSet() bool {
	return v.isSet
}

func (v *NullableSpecifiesColorRangeOptionsForColoringAHeatmapChart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpecifiesColorRangeOptionsForColoringAHeatmapChart(val *SpecifiesColorRangeOptionsForColoringAHeatmapChart) *NullableSpecifiesColorRangeOptionsForColoringAHeatmapChart {
	return &NullableSpecifiesColorRangeOptionsForColoringAHeatmapChart{value: val, isSet: true}
}

func (v NullableSpecifiesColorRangeOptionsForColoringAHeatmapChart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpecifiesColorRangeOptionsForColoringAHeatmapChart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


