/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
	"fmt"
)

// DashboardChartDensity Number of data points displayed in charts in this dashboard 
type DashboardChartDensity string

// List of DashboardChartDensity
const (
	DEFAULT DashboardChartDensity = "DEFAULT"
	LOW DashboardChartDensity = "LOW"
	HIGH DashboardChartDensity = "HIGH"
	HIGHEST DashboardChartDensity = "HIGHEST"
)

// All allowed values of DashboardChartDensity enum
var AllowedDashboardChartDensityEnumValues = []DashboardChartDensity{
	"DEFAULT",
	"LOW",
	"HIGH",
	"HIGHEST",
}

func (v *DashboardChartDensity) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DashboardChartDensity(value)
	for _, existing := range AllowedDashboardChartDensityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DashboardChartDensity", value)
}

// NewDashboardChartDensityFromValue returns a pointer to a valid DashboardChartDensity
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDashboardChartDensityFromValue(v string) (*DashboardChartDensity, error) {
	ev := DashboardChartDensity(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DashboardChartDensity: valid values are %v", v, AllowedDashboardChartDensityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DashboardChartDensity) IsValid() bool {
	for _, existing := range AllowedDashboardChartDensityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DashboardChartDensity value
func (v DashboardChartDensity) Ptr() *DashboardChartDensity {
	return &v
}

type NullableDashboardChartDensity struct {
	value *DashboardChartDensity
	isSet bool
}

func (v NullableDashboardChartDensity) Get() *DashboardChartDensity {
	return v.value
}

func (v *NullableDashboardChartDensity) Set(val *DashboardChartDensity) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardChartDensity) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardChartDensity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardChartDensity(val *DashboardChartDensity) *NullableDashboardChartDensity {
	return &NullableDashboardChartDensity{value: val, isSet: true}
}

func (v NullableDashboardChartDensity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardChartDensity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

