/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Metric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Metric{}

// Metric Metric to display on a navigator 
type Metric struct {
	ColoringScheme *ColoringScheme `json:"coloringScheme,omitempty"`
	// Description of the metric 
	Description *string `json:"description,omitempty"`
	// Metric display name 
	DisplayName *string `json:"displayName,omitempty"`
	Job Job `json:"job"`
	// Metric name 
	Id string `json:"id"`
	// Metric type 
	Type string `json:"type"`
	// Metric value label 
	ValueLabel *string `json:"valueLabel,omitempty"`
	// Metric value format 
	ValueFormat *string `json:"valueFormat,omitempty"`
	// List of metric selectors  
	MetricSelectors []string `json:"metricSelectors"`
}

type _Metric Metric

// NewMetric instantiates a new Metric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetric(job Job, id string, type_ string, metricSelectors []string) *Metric {
	this := Metric{}
	this.Job = job
	this.Id = id
	this.Type = type_
	this.MetricSelectors = metricSelectors
	return &this
}

// NewMetricWithDefaults instantiates a new Metric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricWithDefaults() *Metric {
	this := Metric{}
	return &this
}

// GetColoringScheme returns the ColoringScheme field value if set, zero value otherwise.
func (o *Metric) GetColoringScheme() ColoringScheme {
	if o == nil || IsNil(o.ColoringScheme) {
		var ret ColoringScheme
		return ret
	}
	return *o.ColoringScheme
}

// GetColoringSchemeOk returns a tuple with the ColoringScheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Metric) GetColoringSchemeOk() (*ColoringScheme, bool) {
	if o == nil || IsNil(o.ColoringScheme) {
		return nil, false
	}
	return o.ColoringScheme, true
}

// HasColoringScheme returns a boolean if a field has been set.
func (o *Metric) HasColoringScheme() bool {
	if o != nil && !IsNil(o.ColoringScheme) {
		return true
	}

	return false
}

// SetColoringScheme gets a reference to the given ColoringScheme and assigns it to the ColoringScheme field.
func (o *Metric) SetColoringScheme(v ColoringScheme) {
	o.ColoringScheme = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Metric) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Metric) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Metric) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Metric) SetDescription(v string) {
	o.Description = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *Metric) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Metric) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *Metric) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *Metric) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetJob returns the Job field value
func (o *Metric) GetJob() Job {
	if o == nil {
		var ret Job
		return ret
	}

	return o.Job
}

// GetJobOk returns a tuple with the Job field value
// and a boolean to check if the value has been set.
func (o *Metric) GetJobOk() (*Job, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Job, true
}

// SetJob sets field value
func (o *Metric) SetJob(v Job) {
	o.Job = v
}

// GetId returns the Id field value
func (o *Metric) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Metric) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Metric) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *Metric) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Metric) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Metric) SetType(v string) {
	o.Type = v
}

// GetValueLabel returns the ValueLabel field value if set, zero value otherwise.
func (o *Metric) GetValueLabel() string {
	if o == nil || IsNil(o.ValueLabel) {
		var ret string
		return ret
	}
	return *o.ValueLabel
}

// GetValueLabelOk returns a tuple with the ValueLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Metric) GetValueLabelOk() (*string, bool) {
	if o == nil || IsNil(o.ValueLabel) {
		return nil, false
	}
	return o.ValueLabel, true
}

// HasValueLabel returns a boolean if a field has been set.
func (o *Metric) HasValueLabel() bool {
	if o != nil && !IsNil(o.ValueLabel) {
		return true
	}

	return false
}

// SetValueLabel gets a reference to the given string and assigns it to the ValueLabel field.
func (o *Metric) SetValueLabel(v string) {
	o.ValueLabel = &v
}

// GetValueFormat returns the ValueFormat field value if set, zero value otherwise.
func (o *Metric) GetValueFormat() string {
	if o == nil || IsNil(o.ValueFormat) {
		var ret string
		return ret
	}
	return *o.ValueFormat
}

// GetValueFormatOk returns a tuple with the ValueFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Metric) GetValueFormatOk() (*string, bool) {
	if o == nil || IsNil(o.ValueFormat) {
		return nil, false
	}
	return o.ValueFormat, true
}

// HasValueFormat returns a boolean if a field has been set.
func (o *Metric) HasValueFormat() bool {
	if o != nil && !IsNil(o.ValueFormat) {
		return true
	}

	return false
}

// SetValueFormat gets a reference to the given string and assigns it to the ValueFormat field.
func (o *Metric) SetValueFormat(v string) {
	o.ValueFormat = &v
}

// GetMetricSelectors returns the MetricSelectors field value
func (o *Metric) GetMetricSelectors() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.MetricSelectors
}

// GetMetricSelectorsOk returns a tuple with the MetricSelectors field value
// and a boolean to check if the value has been set.
func (o *Metric) GetMetricSelectorsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MetricSelectors, true
}

// SetMetricSelectors sets field value
func (o *Metric) SetMetricSelectors(v []string) {
	o.MetricSelectors = v
}

func (o Metric) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Metric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ColoringScheme) {
		toSerialize["coloringScheme"] = o.ColoringScheme
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	toSerialize["job"] = o.Job
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	if !IsNil(o.ValueLabel) {
		toSerialize["valueLabel"] = o.ValueLabel
	}
	if !IsNil(o.ValueFormat) {
		toSerialize["valueFormat"] = o.ValueFormat
	}
	toSerialize["metricSelectors"] = o.MetricSelectors
	return toSerialize, nil
}

func (o *Metric) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job",
		"id",
		"type",
		"metricSelectors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMetric := _Metric{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMetric)

	if err != nil {
		return err
	}

	*o = Metric(varMetric)

	return err
}

type NullableMetric struct {
	value *Metric
	isSet bool
}

func (v NullableMetric) Get() *Metric {
	return v.value
}

func (v *NullableMetric) Set(val *Metric) {
	v.value = val
	v.isSet = true
}

func (v NullableMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetric(val *Metric) *NullableMetric {
	return &NullableMetric{value: val, isSet: true}
}

func (v NullableMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


