/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PropertyValuesToFilter - Property values to filter 
type PropertyValuesToFilter struct {
	ArrayOfString *[]string
	String *string
}

// []stringAsPropertyValuesToFilter is a convenience function that returns []string wrapped in PropertyValuesToFilter
func ArrayOfStringAsPropertyValuesToFilter(v *[]string) PropertyValuesToFilter {
	return PropertyValuesToFilter{
		ArrayOfString: v,
	}
}

// stringAsPropertyValuesToFilter is a convenience function that returns string wrapped in PropertyValuesToFilter
func StringAsPropertyValuesToFilter(v *string) PropertyValuesToFilter {
	return PropertyValuesToFilter{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PropertyValuesToFilter) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfString
	err = newStrictDecoder(data).Decode(&dst.ArrayOfString)
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			if err = validator.Validate(dst.ArrayOfString); err != nil {
				dst.ArrayOfString = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfString = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfString = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PropertyValuesToFilter)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
        if err != nil {
            return fmt.Errorf("data failed to match schemas in oneOf(PropertyValuesToFilter): %v", err)
        } else {
            return fmt.Errorf("data failed to match schemas in oneOf(PropertyValuesToFilter)")
        }
        if err != nil {
            return fmt.Errorf("data failed to match schemas in oneOf(PropertyValuesToFilter): %v", err)
        } else {
            return fmt.Errorf("data failed to match schemas in oneOf(PropertyValuesToFilter)")
        }
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PropertyValuesToFilter) MarshalJSON() ([]byte, error) {
	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PropertyValuesToFilter) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfString != nil {
		return obj.ArrayOfString
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PropertyValuesToFilter) GetActualInstanceValue() (interface{}) {
	if obj.ArrayOfString != nil {
		return *obj.ArrayOfString
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePropertyValuesToFilter struct {
	value *PropertyValuesToFilter
	isSet bool
}

func (v NullablePropertyValuesToFilter) Get() *PropertyValuesToFilter {
	return v.value
}

func (v *NullablePropertyValuesToFilter) Set(val *PropertyValuesToFilter) {
	v.value = val
	v.isSet = true
}

func (v NullablePropertyValuesToFilter) IsSet() bool {
	return v.isSet
}

func (v *NullablePropertyValuesToFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePropertyValuesToFilter(val *PropertyValuesToFilter) *NullablePropertyValuesToFilter {
	return &NullablePropertyValuesToFilter{value: val, isSet: true}
}

func (v NullablePropertyValuesToFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePropertyValuesToFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


