/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the DashboardChartsFilters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardChartsFilters{}

// DashboardChartsFilters List of filters to apply to all the charts in a dashboard 
type DashboardChartsFilters struct {
	// List of filters to apply to charts in the dashboard 
	Sources []DashboardChartsSingleFilter `json:"sources,omitempty"`
	Time *DashboardChartsFiltersTime `json:"time,omitempty"`
	// List of filters for use in the UI 
	Variables []DashboardChartsWebUIFilter `json:"variables,omitempty"`
}

// NewDashboardChartsFilters instantiates a new DashboardChartsFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardChartsFilters() *DashboardChartsFilters {
	this := DashboardChartsFilters{}
	return &this
}

// NewDashboardChartsFiltersWithDefaults instantiates a new DashboardChartsFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardChartsFiltersWithDefaults() *DashboardChartsFilters {
	this := DashboardChartsFilters{}
	return &this
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *DashboardChartsFilters) GetSources() []DashboardChartsSingleFilter {
	if o == nil || IsNil(o.Sources) {
		var ret []DashboardChartsSingleFilter
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardChartsFilters) GetSourcesOk() ([]DashboardChartsSingleFilter, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *DashboardChartsFilters) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given []DashboardChartsSingleFilter and assigns it to the Sources field.
func (o *DashboardChartsFilters) SetSources(v []DashboardChartsSingleFilter) {
	o.Sources = v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *DashboardChartsFilters) GetTime() DashboardChartsFiltersTime {
	if o == nil || IsNil(o.Time) {
		var ret DashboardChartsFiltersTime
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardChartsFilters) GetTimeOk() (*DashboardChartsFiltersTime, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *DashboardChartsFilters) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given DashboardChartsFiltersTime and assigns it to the Time field.
func (o *DashboardChartsFilters) SetTime(v DashboardChartsFiltersTime) {
	o.Time = &v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *DashboardChartsFilters) GetVariables() []DashboardChartsWebUIFilter {
	if o == nil || IsNil(o.Variables) {
		var ret []DashboardChartsWebUIFilter
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardChartsFilters) GetVariablesOk() ([]DashboardChartsWebUIFilter, bool) {
	if o == nil || IsNil(o.Variables) {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *DashboardChartsFilters) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given []DashboardChartsWebUIFilter and assigns it to the Variables field.
func (o *DashboardChartsFilters) SetVariables(v []DashboardChartsWebUIFilter) {
	o.Variables = v
}

func (o DashboardChartsFilters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardChartsFilters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	return toSerialize, nil
}

type NullableDashboardChartsFilters struct {
	value *DashboardChartsFilters
	isSet bool
}

func (v NullableDashboardChartsFilters) Get() *DashboardChartsFilters {
	return v.value
}

func (v *NullableDashboardChartsFilters) Set(val *DashboardChartsFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardChartsFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardChartsFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardChartsFilters(val *DashboardChartsFilters) *NullableDashboardChartsFilters {
	return &NullableDashboardChartsFilters{value: val, isSet: true}
}

func (v NullableDashboardChartsFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardChartsFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


