/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the AggregateDashboardsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggregateDashboardsInner{}

// AggregateDashboardsInner struct for AggregateDashboardsInner
type AggregateDashboardsInner struct {
	AuthorizedWriters *DashboardAuthorizedWriters `json:"authorizedWriters,omitempty"`
	ChartDensity *DashboardChartDensity `json:"chartDensity,omitempty"`
	// List of chart IDs and settings for the charts associated with this dashboard 
	Charts []DashboardChartSettingsObject `json:"charts,omitempty"`
	// Dashboard creation timestamp, in *nix time in milliseconds. Set by system. 
	Created *int64 `json:"created,omitempty"`
	// User ID of dashboard creator. Set by system. 
	Creator *string `json:"creator,omitempty"`
	// not used 
	CustomProperties *string `json:"customProperties,omitempty"`
	// Dashboard description 
	Description *string `json:"description,omitempty"`
	// Reserved for system use 
	DiscoveryOptions map[string]interface{} `json:"discoveryOptions,omitempty"`
	// List of event overlays you can apply to charts in this dashboard 
	EventOverlays []DashboardEventOverlayFilter `json:"eventOverlays,omitempty"`
	Filters *DashboardChartsFilters `json:"filters,omitempty"`
	// ID of an existing dashboard group that you want to contain this dashboard 
	GroupId *string `json:"groupId,omitempty"`
	// The ID of the dashboard. Set by system. 
	Id *string `json:"id,omitempty"`
	// Dashboard last updated time, in *nix format in milliseconds. Set by system. 
	LastUpdated *int64 `json:"lastUpdated,omitempty"`
	// ID of user who last updated the dashboard. Set by system. 
	LastUpdatedBy *string `json:"lastUpdatedBy,omitempty"`
	// In milliseconds, the time to wait for data points before ignoring them 
	MaxDelayOverride *int32 `json:"maxDelayOverride,omitempty"`
	// Dashboard name in the user interface 
	Name *string `json:"name,omitempty"`
	// List of active event overlays for charts in this dashboard 
	SelectedEventOverlays []DashboardChartEventOverlay `json:"selectedEventOverlays,omitempty"`
	// not used 
	Tags []string `json:"tags,omitempty"`
	Permissions *DashboardPermissions `json:"permissions,omitempty"`
}

// NewAggregateDashboardsInner instantiates a new AggregateDashboardsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregateDashboardsInner() *AggregateDashboardsInner {
	this := AggregateDashboardsInner{}
	var chartDensity DashboardChartDensity = DEFAULT
	this.ChartDensity = &chartDensity
	return &this
}

// NewAggregateDashboardsInnerWithDefaults instantiates a new AggregateDashboardsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregateDashboardsInnerWithDefaults() *AggregateDashboardsInner {
	this := AggregateDashboardsInner{}
	var chartDensity DashboardChartDensity = DEFAULT
	this.ChartDensity = &chartDensity
	return &this
}

// GetAuthorizedWriters returns the AuthorizedWriters field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetAuthorizedWriters() DashboardAuthorizedWriters {
	if o == nil || IsNil(o.AuthorizedWriters) {
		var ret DashboardAuthorizedWriters
		return ret
	}
	return *o.AuthorizedWriters
}

// GetAuthorizedWritersOk returns a tuple with the AuthorizedWriters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetAuthorizedWritersOk() (*DashboardAuthorizedWriters, bool) {
	if o == nil || IsNil(o.AuthorizedWriters) {
		return nil, false
	}
	return o.AuthorizedWriters, true
}

// HasAuthorizedWriters returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasAuthorizedWriters() bool {
	if o != nil && !IsNil(o.AuthorizedWriters) {
		return true
	}

	return false
}

// SetAuthorizedWriters gets a reference to the given DashboardAuthorizedWriters and assigns it to the AuthorizedWriters field.
func (o *AggregateDashboardsInner) SetAuthorizedWriters(v DashboardAuthorizedWriters) {
	o.AuthorizedWriters = &v
}

// GetChartDensity returns the ChartDensity field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetChartDensity() DashboardChartDensity {
	if o == nil || IsNil(o.ChartDensity) {
		var ret DashboardChartDensity
		return ret
	}
	return *o.ChartDensity
}

// GetChartDensityOk returns a tuple with the ChartDensity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetChartDensityOk() (*DashboardChartDensity, bool) {
	if o == nil || IsNil(o.ChartDensity) {
		return nil, false
	}
	return o.ChartDensity, true
}

// HasChartDensity returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasChartDensity() bool {
	if o != nil && !IsNil(o.ChartDensity) {
		return true
	}

	return false
}

// SetChartDensity gets a reference to the given DashboardChartDensity and assigns it to the ChartDensity field.
func (o *AggregateDashboardsInner) SetChartDensity(v DashboardChartDensity) {
	o.ChartDensity = &v
}

// GetCharts returns the Charts field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetCharts() []DashboardChartSettingsObject {
	if o == nil || IsNil(o.Charts) {
		var ret []DashboardChartSettingsObject
		return ret
	}
	return o.Charts
}

// GetChartsOk returns a tuple with the Charts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetChartsOk() ([]DashboardChartSettingsObject, bool) {
	if o == nil || IsNil(o.Charts) {
		return nil, false
	}
	return o.Charts, true
}

// HasCharts returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasCharts() bool {
	if o != nil && !IsNil(o.Charts) {
		return true
	}

	return false
}

// SetCharts gets a reference to the given []DashboardChartSettingsObject and assigns it to the Charts field.
func (o *AggregateDashboardsInner) SetCharts(v []DashboardChartSettingsObject) {
	o.Charts = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetCreated() int64 {
	if o == nil || IsNil(o.Created) {
		var ret int64
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetCreatedOk() (*int64, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given int64 and assigns it to the Created field.
func (o *AggregateDashboardsInner) SetCreated(v int64) {
	o.Created = &v
}

// GetCreator returns the Creator field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetCreator() string {
	if o == nil || IsNil(o.Creator) {
		var ret string
		return ret
	}
	return *o.Creator
}

// GetCreatorOk returns a tuple with the Creator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetCreatorOk() (*string, bool) {
	if o == nil || IsNil(o.Creator) {
		return nil, false
	}
	return o.Creator, true
}

// HasCreator returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasCreator() bool {
	if o != nil && !IsNil(o.Creator) {
		return true
	}

	return false
}

// SetCreator gets a reference to the given string and assigns it to the Creator field.
func (o *AggregateDashboardsInner) SetCreator(v string) {
	o.Creator = &v
}

// GetCustomProperties returns the CustomProperties field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetCustomProperties() string {
	if o == nil || IsNil(o.CustomProperties) {
		var ret string
		return ret
	}
	return *o.CustomProperties
}

// GetCustomPropertiesOk returns a tuple with the CustomProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetCustomPropertiesOk() (*string, bool) {
	if o == nil || IsNil(o.CustomProperties) {
		return nil, false
	}
	return o.CustomProperties, true
}

// HasCustomProperties returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasCustomProperties() bool {
	if o != nil && !IsNil(o.CustomProperties) {
		return true
	}

	return false
}

// SetCustomProperties gets a reference to the given string and assigns it to the CustomProperties field.
func (o *AggregateDashboardsInner) SetCustomProperties(v string) {
	o.CustomProperties = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AggregateDashboardsInner) SetDescription(v string) {
	o.Description = &v
}

// GetDiscoveryOptions returns the DiscoveryOptions field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetDiscoveryOptions() map[string]interface{} {
	if o == nil || IsNil(o.DiscoveryOptions) {
		var ret map[string]interface{}
		return ret
	}
	return o.DiscoveryOptions
}

// GetDiscoveryOptionsOk returns a tuple with the DiscoveryOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetDiscoveryOptionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DiscoveryOptions) {
		return map[string]interface{}{}, false
	}
	return o.DiscoveryOptions, true
}

// HasDiscoveryOptions returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasDiscoveryOptions() bool {
	if o != nil && !IsNil(o.DiscoveryOptions) {
		return true
	}

	return false
}

// SetDiscoveryOptions gets a reference to the given map[string]interface{} and assigns it to the DiscoveryOptions field.
func (o *AggregateDashboardsInner) SetDiscoveryOptions(v map[string]interface{}) {
	o.DiscoveryOptions = v
}

// GetEventOverlays returns the EventOverlays field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetEventOverlays() []DashboardEventOverlayFilter {
	if o == nil || IsNil(o.EventOverlays) {
		var ret []DashboardEventOverlayFilter
		return ret
	}
	return o.EventOverlays
}

// GetEventOverlaysOk returns a tuple with the EventOverlays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetEventOverlaysOk() ([]DashboardEventOverlayFilter, bool) {
	if o == nil || IsNil(o.EventOverlays) {
		return nil, false
	}
	return o.EventOverlays, true
}

// HasEventOverlays returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasEventOverlays() bool {
	if o != nil && !IsNil(o.EventOverlays) {
		return true
	}

	return false
}

// SetEventOverlays gets a reference to the given []DashboardEventOverlayFilter and assigns it to the EventOverlays field.
func (o *AggregateDashboardsInner) SetEventOverlays(v []DashboardEventOverlayFilter) {
	o.EventOverlays = v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetFilters() DashboardChartsFilters {
	if o == nil || IsNil(o.Filters) {
		var ret DashboardChartsFilters
		return ret
	}
	return *o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetFiltersOk() (*DashboardChartsFilters, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given DashboardChartsFilters and assigns it to the Filters field.
func (o *AggregateDashboardsInner) SetFilters(v DashboardChartsFilters) {
	o.Filters = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetGroupId() string {
	if o == nil || IsNil(o.GroupId) {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *AggregateDashboardsInner) SetGroupId(v string) {
	o.GroupId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AggregateDashboardsInner) SetId(v string) {
	o.Id = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetLastUpdated() int64 {
	if o == nil || IsNil(o.LastUpdated) {
		var ret int64
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetLastUpdatedOk() (*int64, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given int64 and assigns it to the LastUpdated field.
func (o *AggregateDashboardsInner) SetLastUpdated(v int64) {
	o.LastUpdated = &v
}

// GetLastUpdatedBy returns the LastUpdatedBy field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetLastUpdatedBy() string {
	if o == nil || IsNil(o.LastUpdatedBy) {
		var ret string
		return ret
	}
	return *o.LastUpdatedBy
}

// GetLastUpdatedByOk returns a tuple with the LastUpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetLastUpdatedByOk() (*string, bool) {
	if o == nil || IsNil(o.LastUpdatedBy) {
		return nil, false
	}
	return o.LastUpdatedBy, true
}

// HasLastUpdatedBy returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasLastUpdatedBy() bool {
	if o != nil && !IsNil(o.LastUpdatedBy) {
		return true
	}

	return false
}

// SetLastUpdatedBy gets a reference to the given string and assigns it to the LastUpdatedBy field.
func (o *AggregateDashboardsInner) SetLastUpdatedBy(v string) {
	o.LastUpdatedBy = &v
}

// GetMaxDelayOverride returns the MaxDelayOverride field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetMaxDelayOverride() int32 {
	if o == nil || IsNil(o.MaxDelayOverride) {
		var ret int32
		return ret
	}
	return *o.MaxDelayOverride
}

// GetMaxDelayOverrideOk returns a tuple with the MaxDelayOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetMaxDelayOverrideOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxDelayOverride) {
		return nil, false
	}
	return o.MaxDelayOverride, true
}

// HasMaxDelayOverride returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasMaxDelayOverride() bool {
	if o != nil && !IsNil(o.MaxDelayOverride) {
		return true
	}

	return false
}

// SetMaxDelayOverride gets a reference to the given int32 and assigns it to the MaxDelayOverride field.
func (o *AggregateDashboardsInner) SetMaxDelayOverride(v int32) {
	o.MaxDelayOverride = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AggregateDashboardsInner) SetName(v string) {
	o.Name = &v
}

// GetSelectedEventOverlays returns the SelectedEventOverlays field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetSelectedEventOverlays() []DashboardChartEventOverlay {
	if o == nil || IsNil(o.SelectedEventOverlays) {
		var ret []DashboardChartEventOverlay
		return ret
	}
	return o.SelectedEventOverlays
}

// GetSelectedEventOverlaysOk returns a tuple with the SelectedEventOverlays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetSelectedEventOverlaysOk() ([]DashboardChartEventOverlay, bool) {
	if o == nil || IsNil(o.SelectedEventOverlays) {
		return nil, false
	}
	return o.SelectedEventOverlays, true
}

// HasSelectedEventOverlays returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasSelectedEventOverlays() bool {
	if o != nil && !IsNil(o.SelectedEventOverlays) {
		return true
	}

	return false
}

// SetSelectedEventOverlays gets a reference to the given []DashboardChartEventOverlay and assigns it to the SelectedEventOverlays field.
func (o *AggregateDashboardsInner) SetSelectedEventOverlays(v []DashboardChartEventOverlay) {
	o.SelectedEventOverlays = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *AggregateDashboardsInner) SetTags(v []string) {
	o.Tags = v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *AggregateDashboardsInner) GetPermissions() DashboardPermissions {
	if o == nil || IsNil(o.Permissions) {
		var ret DashboardPermissions
		return ret
	}
	return *o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateDashboardsInner) GetPermissionsOk() (*DashboardPermissions, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *AggregateDashboardsInner) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given DashboardPermissions and assigns it to the Permissions field.
func (o *AggregateDashboardsInner) SetPermissions(v DashboardPermissions) {
	o.Permissions = &v
}

func (o AggregateDashboardsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggregateDashboardsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthorizedWriters) {
		toSerialize["authorizedWriters"] = o.AuthorizedWriters
	}
	if !IsNil(o.ChartDensity) {
		toSerialize["chartDensity"] = o.ChartDensity
	}
	if !IsNil(o.Charts) {
		toSerialize["charts"] = o.Charts
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Creator) {
		toSerialize["creator"] = o.Creator
	}
	if !IsNil(o.CustomProperties) {
		toSerialize["customProperties"] = o.CustomProperties
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DiscoveryOptions) {
		toSerialize["discoveryOptions"] = o.DiscoveryOptions
	}
	if !IsNil(o.EventOverlays) {
		toSerialize["eventOverlays"] = o.EventOverlays
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if !IsNil(o.GroupId) {
		toSerialize["groupId"] = o.GroupId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["lastUpdated"] = o.LastUpdated
	}
	if !IsNil(o.LastUpdatedBy) {
		toSerialize["lastUpdatedBy"] = o.LastUpdatedBy
	}
	if !IsNil(o.MaxDelayOverride) {
		toSerialize["maxDelayOverride"] = o.MaxDelayOverride
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.SelectedEventOverlays) {
		toSerialize["selectedEventOverlays"] = o.SelectedEventOverlays
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return toSerialize, nil
}

type NullableAggregateDashboardsInner struct {
	value *AggregateDashboardsInner
	isSet bool
}

func (v NullableAggregateDashboardsInner) Get() *AggregateDashboardsInner {
	return v.value
}

func (v *NullableAggregateDashboardsInner) Set(val *AggregateDashboardsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregateDashboardsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregateDashboardsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregateDashboardsInner(val *AggregateDashboardsInner) *NullableAggregateDashboardsInner {
	return &NullableAggregateDashboardsInner{value: val, isSet: true}
}

func (v NullableAggregateDashboardsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregateDashboardsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


