/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the GetNavigatorsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNavigatorsResponse{}

// GetNavigatorsResponse Retrieving navigators by query endpoint response body 
type GetNavigatorsResponse struct {
	// Number of matched navigators 
	Count *int32 `json:"count,omitempty"`
	// List of navigators 
	Results []GetNavigatorsResult `json:"results,omitempty"`
}

// NewGetNavigatorsResponse instantiates a new GetNavigatorsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNavigatorsResponse() *GetNavigatorsResponse {
	this := GetNavigatorsResponse{}
	return &this
}

// NewGetNavigatorsResponseWithDefaults instantiates a new GetNavigatorsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNavigatorsResponseWithDefaults() *GetNavigatorsResponse {
	this := GetNavigatorsResponse{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *GetNavigatorsResponse) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorsResponse) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *GetNavigatorsResponse) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *GetNavigatorsResponse) SetCount(v int32) {
	o.Count = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *GetNavigatorsResponse) GetResults() []GetNavigatorsResult {
	if o == nil || IsNil(o.Results) {
		var ret []GetNavigatorsResult
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorsResponse) GetResultsOk() ([]GetNavigatorsResult, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *GetNavigatorsResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []GetNavigatorsResult and assigns it to the Results field.
func (o *GetNavigatorsResponse) SetResults(v []GetNavigatorsResult) {
	o.Results = v
}

func (o GetNavigatorsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNavigatorsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableGetNavigatorsResponse struct {
	value *GetNavigatorsResponse
	isSet bool
}

func (v NullableGetNavigatorsResponse) Get() *GetNavigatorsResponse {
	return v.value
}

func (v *NullableGetNavigatorsResponse) Set(val *GetNavigatorsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNavigatorsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNavigatorsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNavigatorsResponse(val *GetNavigatorsResponse) *NullableGetNavigatorsResponse {
	return &NullableGetNavigatorsResponse{value: val, isSet: true}
}

func (v NullableGetNavigatorsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNavigatorsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


