/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the DeleteSingleNavigator403Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteSingleNavigator403Response{}

// DeleteSingleNavigator403Response struct for DeleteSingleNavigator403Response
type DeleteSingleNavigator403Response struct {
	// HTTP response code 
	Code *int32 `json:"code,omitempty"`
	// Error explanation 
	Message *string `json:"message,omitempty"`
}

// NewDeleteSingleNavigator403Response instantiates a new DeleteSingleNavigator403Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteSingleNavigator403Response() *DeleteSingleNavigator403Response {
	this := DeleteSingleNavigator403Response{}
	return &this
}

// NewDeleteSingleNavigator403ResponseWithDefaults instantiates a new DeleteSingleNavigator403Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteSingleNavigator403ResponseWithDefaults() *DeleteSingleNavigator403Response {
	this := DeleteSingleNavigator403Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *DeleteSingleNavigator403Response) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteSingleNavigator403Response) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *DeleteSingleNavigator403Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *DeleteSingleNavigator403Response) SetCode(v int32) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DeleteSingleNavigator403Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteSingleNavigator403Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DeleteSingleNavigator403Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DeleteSingleNavigator403Response) SetMessage(v string) {
	o.Message = &v
}

func (o DeleteSingleNavigator403Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteSingleNavigator403Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableDeleteSingleNavigator403Response struct {
	value *DeleteSingleNavigator403Response
	isSet bool
}

func (v NullableDeleteSingleNavigator403Response) Get() *DeleteSingleNavigator403Response {
	return v.value
}

func (v *NullableDeleteSingleNavigator403Response) Set(val *DeleteSingleNavigator403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteSingleNavigator403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteSingleNavigator403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteSingleNavigator403Response(val *DeleteSingleNavigator403Response) *NullableDeleteSingleNavigator403Response {
	return &NullableDeleteSingleNavigator403Response{value: val, isSet: true}
}

func (v NullableDeleteSingleNavigator403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteSingleNavigator403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


