/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the GeneralOptionsForTheChart type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeneralOptionsForTheChart{}

// GeneralOptionsForTheChart Set of options that control the appearance and operation of the chart 
type GeneralOptionsForTheChart struct {
	// Controls sampling display 
	DisableSampling *bool `json:"disableSampling,omitempty"`
	// In milliseconds, the time to wait before ignoring future data points 
	MaxDelay *int32 `json:"maxDelay,omitempty"`
	// Minimum computation resolution 
	MinimumResolution *int32 `json:"minimumResolution,omitempty"`
}

// NewGeneralOptionsForTheChart instantiates a new GeneralOptionsForTheChart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeneralOptionsForTheChart() *GeneralOptionsForTheChart {
	this := GeneralOptionsForTheChart{}
	var disableSampling bool = false
	this.DisableSampling = &disableSampling
	return &this
}

// NewGeneralOptionsForTheChartWithDefaults instantiates a new GeneralOptionsForTheChart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeneralOptionsForTheChartWithDefaults() *GeneralOptionsForTheChart {
	this := GeneralOptionsForTheChart{}
	var disableSampling bool = false
	this.DisableSampling = &disableSampling
	return &this
}

// GetDisableSampling returns the DisableSampling field value if set, zero value otherwise.
func (o *GeneralOptionsForTheChart) GetDisableSampling() bool {
	if o == nil || IsNil(o.DisableSampling) {
		var ret bool
		return ret
	}
	return *o.DisableSampling
}

// GetDisableSamplingOk returns a tuple with the DisableSampling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralOptionsForTheChart) GetDisableSamplingOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableSampling) {
		return nil, false
	}
	return o.DisableSampling, true
}

// HasDisableSampling returns a boolean if a field has been set.
func (o *GeneralOptionsForTheChart) HasDisableSampling() bool {
	if o != nil && !IsNil(o.DisableSampling) {
		return true
	}

	return false
}

// SetDisableSampling gets a reference to the given bool and assigns it to the DisableSampling field.
func (o *GeneralOptionsForTheChart) SetDisableSampling(v bool) {
	o.DisableSampling = &v
}

// GetMaxDelay returns the MaxDelay field value if set, zero value otherwise.
func (o *GeneralOptionsForTheChart) GetMaxDelay() int32 {
	if o == nil || IsNil(o.MaxDelay) {
		var ret int32
		return ret
	}
	return *o.MaxDelay
}

// GetMaxDelayOk returns a tuple with the MaxDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralOptionsForTheChart) GetMaxDelayOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxDelay) {
		return nil, false
	}
	return o.MaxDelay, true
}

// HasMaxDelay returns a boolean if a field has been set.
func (o *GeneralOptionsForTheChart) HasMaxDelay() bool {
	if o != nil && !IsNil(o.MaxDelay) {
		return true
	}

	return false
}

// SetMaxDelay gets a reference to the given int32 and assigns it to the MaxDelay field.
func (o *GeneralOptionsForTheChart) SetMaxDelay(v int32) {
	o.MaxDelay = &v
}

// GetMinimumResolution returns the MinimumResolution field value if set, zero value otherwise.
func (o *GeneralOptionsForTheChart) GetMinimumResolution() int32 {
	if o == nil || IsNil(o.MinimumResolution) {
		var ret int32
		return ret
	}
	return *o.MinimumResolution
}

// GetMinimumResolutionOk returns a tuple with the MinimumResolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneralOptionsForTheChart) GetMinimumResolutionOk() (*int32, bool) {
	if o == nil || IsNil(o.MinimumResolution) {
		return nil, false
	}
	return o.MinimumResolution, true
}

// HasMinimumResolution returns a boolean if a field has been set.
func (o *GeneralOptionsForTheChart) HasMinimumResolution() bool {
	if o != nil && !IsNil(o.MinimumResolution) {
		return true
	}

	return false
}

// SetMinimumResolution gets a reference to the given int32 and assigns it to the MinimumResolution field.
func (o *GeneralOptionsForTheChart) SetMinimumResolution(v int32) {
	o.MinimumResolution = &v
}

func (o GeneralOptionsForTheChart) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeneralOptionsForTheChart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisableSampling) {
		toSerialize["disableSampling"] = o.DisableSampling
	}
	if !IsNil(o.MaxDelay) {
		toSerialize["maxDelay"] = o.MaxDelay
	}
	if !IsNil(o.MinimumResolution) {
		toSerialize["minimumResolution"] = o.MinimumResolution
	}
	return toSerialize, nil
}

type NullableGeneralOptionsForTheChart struct {
	value *GeneralOptionsForTheChart
	isSet bool
}

func (v NullableGeneralOptionsForTheChart) Get() *GeneralOptionsForTheChart {
	return v.value
}

func (v *NullableGeneralOptionsForTheChart) Set(val *GeneralOptionsForTheChart) {
	v.value = val
	v.isSet = true
}

func (v NullableGeneralOptionsForTheChart) IsSet() bool {
	return v.isSet
}

func (v *NullableGeneralOptionsForTheChart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeneralOptionsForTheChart(val *GeneralOptionsForTheChart) *NullableGeneralOptionsForTheChart {
	return &NullableGeneralOptionsForTheChart{value: val, isSet: true}
}

func (v NullableGeneralOptionsForTheChart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeneralOptionsForTheChart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


