/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the GetNavigatorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNavigatorResponse{}

// GetNavigatorResponse Properties of an individual navigator 
type GetNavigatorResponse struct {
	// Array of dashboard IDs to use for aggregate display. Specific to GET /navigator. 
	AggregateDashboards []string `json:"aggregateDashboards,omitempty"`
	// Navigator alert query 
	AlertQuery *string `json:"alertQuery,omitempty"`
	// Navigator categories list 
	Categories []Category `json:"categories,omitempty"`
	// Navigator creation time 
	Created *int64 `json:"created,omitempty"`
	// User ID of the user who created this navigator  
	Creator *string `json:"creator,omitempty"`
	// Navigator default group by  
	DefaultGroupBy *string `json:"defaultGroupBy,omitempty"`
	// Navigator display name 
	DisplayName *string `json:"displayName,omitempty"`
	// Navigator system ID 
	Id *string `json:"id,omitempty"`
	// Navigator ID display name 
	IdDisplayName *string `json:"idDisplayName,omitempty"`
	// Array of dashboard IDs to use for instance display. Specific to GET /navigator. 
	InstanceDashboards []string `json:"instanceDashboards,omitempty"`
	// Instance description to display 
	InstanceDisplayText *string `json:"instanceDisplayText,omitempty"`
	// Navigator instance label 
	InstanceLabel *string `json:"instanceLabel,omitempty"`
	// Time at which the navigator was last updated 
	LastUpdated *int64 `json:"lastUpdated,omitempty"`
	// ID of the user who last updated this navigator 
	LastUpdatedBy *string `json:"lastUpdatedBy,omitempty"`
	// List of columns in navigator 
	ListColumns []ListColumn `json:"listColumns,omitempty"`
	// Navigator unique code 
	NavigatorCode *string `json:"navigatorCode,omitempty"`
	OwnerScope *OwnerScope `json:"ownerScope,omitempty"`
	// Template for ID construction 
	PropertyIdentifierTemplate *string `json:"propertyIdentifierTemplate,omitempty"`
	// Navigator metrics information 
	EntityMetrics []Metric `json:"entityMetrics,omitempty"`
	// Navigator system type identifiers 
	SystemTypes []string `json:"systemTypes,omitempty"`
	// Label for a summary metric 
	SummaryMetricLabel *string `json:"summaryMetricLabel,omitempty"`
	// SignalFlow program for summary metric 
	SummaryMetricProgramText *string `json:"summaryMetricProgramText,omitempty"`
	// A list of keys that appears in the tooltip 
	TooltipKeyList []TooltipKey `json:"tooltipKeyList,omitempty"`
}

// NewGetNavigatorResponse instantiates a new GetNavigatorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNavigatorResponse() *GetNavigatorResponse {
	this := GetNavigatorResponse{}
	return &this
}

// NewGetNavigatorResponseWithDefaults instantiates a new GetNavigatorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNavigatorResponseWithDefaults() *GetNavigatorResponse {
	this := GetNavigatorResponse{}
	return &this
}

// GetAggregateDashboards returns the AggregateDashboards field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetAggregateDashboards() []string {
	if o == nil || IsNil(o.AggregateDashboards) {
		var ret []string
		return ret
	}
	return o.AggregateDashboards
}

// GetAggregateDashboardsOk returns a tuple with the AggregateDashboards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetAggregateDashboardsOk() ([]string, bool) {
	if o == nil || IsNil(o.AggregateDashboards) {
		return nil, false
	}
	return o.AggregateDashboards, true
}

// HasAggregateDashboards returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasAggregateDashboards() bool {
	if o != nil && !IsNil(o.AggregateDashboards) {
		return true
	}

	return false
}

// SetAggregateDashboards gets a reference to the given []string and assigns it to the AggregateDashboards field.
func (o *GetNavigatorResponse) SetAggregateDashboards(v []string) {
	o.AggregateDashboards = v
}

// GetAlertQuery returns the AlertQuery field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetAlertQuery() string {
	if o == nil || IsNil(o.AlertQuery) {
		var ret string
		return ret
	}
	return *o.AlertQuery
}

// GetAlertQueryOk returns a tuple with the AlertQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetAlertQueryOk() (*string, bool) {
	if o == nil || IsNil(o.AlertQuery) {
		return nil, false
	}
	return o.AlertQuery, true
}

// HasAlertQuery returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasAlertQuery() bool {
	if o != nil && !IsNil(o.AlertQuery) {
		return true
	}

	return false
}

// SetAlertQuery gets a reference to the given string and assigns it to the AlertQuery field.
func (o *GetNavigatorResponse) SetAlertQuery(v string) {
	o.AlertQuery = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetCategories() []Category {
	if o == nil || IsNil(o.Categories) {
		var ret []Category
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetCategoriesOk() ([]Category, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []Category and assigns it to the Categories field.
func (o *GetNavigatorResponse) SetCategories(v []Category) {
	o.Categories = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetCreated() int64 {
	if o == nil || IsNil(o.Created) {
		var ret int64
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetCreatedOk() (*int64, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given int64 and assigns it to the Created field.
func (o *GetNavigatorResponse) SetCreated(v int64) {
	o.Created = &v
}

// GetCreator returns the Creator field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetCreator() string {
	if o == nil || IsNil(o.Creator) {
		var ret string
		return ret
	}
	return *o.Creator
}

// GetCreatorOk returns a tuple with the Creator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetCreatorOk() (*string, bool) {
	if o == nil || IsNil(o.Creator) {
		return nil, false
	}
	return o.Creator, true
}

// HasCreator returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasCreator() bool {
	if o != nil && !IsNil(o.Creator) {
		return true
	}

	return false
}

// SetCreator gets a reference to the given string and assigns it to the Creator field.
func (o *GetNavigatorResponse) SetCreator(v string) {
	o.Creator = &v
}

// GetDefaultGroupBy returns the DefaultGroupBy field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetDefaultGroupBy() string {
	if o == nil || IsNil(o.DefaultGroupBy) {
		var ret string
		return ret
	}
	return *o.DefaultGroupBy
}

// GetDefaultGroupByOk returns a tuple with the DefaultGroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetDefaultGroupByOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultGroupBy) {
		return nil, false
	}
	return o.DefaultGroupBy, true
}

// HasDefaultGroupBy returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasDefaultGroupBy() bool {
	if o != nil && !IsNil(o.DefaultGroupBy) {
		return true
	}

	return false
}

// SetDefaultGroupBy gets a reference to the given string and assigns it to the DefaultGroupBy field.
func (o *GetNavigatorResponse) SetDefaultGroupBy(v string) {
	o.DefaultGroupBy = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *GetNavigatorResponse) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetNavigatorResponse) SetId(v string) {
	o.Id = &v
}

// GetIdDisplayName returns the IdDisplayName field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetIdDisplayName() string {
	if o == nil || IsNil(o.IdDisplayName) {
		var ret string
		return ret
	}
	return *o.IdDisplayName
}

// GetIdDisplayNameOk returns a tuple with the IdDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetIdDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.IdDisplayName) {
		return nil, false
	}
	return o.IdDisplayName, true
}

// HasIdDisplayName returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasIdDisplayName() bool {
	if o != nil && !IsNil(o.IdDisplayName) {
		return true
	}

	return false
}

// SetIdDisplayName gets a reference to the given string and assigns it to the IdDisplayName field.
func (o *GetNavigatorResponse) SetIdDisplayName(v string) {
	o.IdDisplayName = &v
}

// GetInstanceDashboards returns the InstanceDashboards field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetInstanceDashboards() []string {
	if o == nil || IsNil(o.InstanceDashboards) {
		var ret []string
		return ret
	}
	return o.InstanceDashboards
}

// GetInstanceDashboardsOk returns a tuple with the InstanceDashboards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetInstanceDashboardsOk() ([]string, bool) {
	if o == nil || IsNil(o.InstanceDashboards) {
		return nil, false
	}
	return o.InstanceDashboards, true
}

// HasInstanceDashboards returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasInstanceDashboards() bool {
	if o != nil && !IsNil(o.InstanceDashboards) {
		return true
	}

	return false
}

// SetInstanceDashboards gets a reference to the given []string and assigns it to the InstanceDashboards field.
func (o *GetNavigatorResponse) SetInstanceDashboards(v []string) {
	o.InstanceDashboards = v
}

// GetInstanceDisplayText returns the InstanceDisplayText field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetInstanceDisplayText() string {
	if o == nil || IsNil(o.InstanceDisplayText) {
		var ret string
		return ret
	}
	return *o.InstanceDisplayText
}

// GetInstanceDisplayTextOk returns a tuple with the InstanceDisplayText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetInstanceDisplayTextOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceDisplayText) {
		return nil, false
	}
	return o.InstanceDisplayText, true
}

// HasInstanceDisplayText returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasInstanceDisplayText() bool {
	if o != nil && !IsNil(o.InstanceDisplayText) {
		return true
	}

	return false
}

// SetInstanceDisplayText gets a reference to the given string and assigns it to the InstanceDisplayText field.
func (o *GetNavigatorResponse) SetInstanceDisplayText(v string) {
	o.InstanceDisplayText = &v
}

// GetInstanceLabel returns the InstanceLabel field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetInstanceLabel() string {
	if o == nil || IsNil(o.InstanceLabel) {
		var ret string
		return ret
	}
	return *o.InstanceLabel
}

// GetInstanceLabelOk returns a tuple with the InstanceLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetInstanceLabelOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceLabel) {
		return nil, false
	}
	return o.InstanceLabel, true
}

// HasInstanceLabel returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasInstanceLabel() bool {
	if o != nil && !IsNil(o.InstanceLabel) {
		return true
	}

	return false
}

// SetInstanceLabel gets a reference to the given string and assigns it to the InstanceLabel field.
func (o *GetNavigatorResponse) SetInstanceLabel(v string) {
	o.InstanceLabel = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetLastUpdated() int64 {
	if o == nil || IsNil(o.LastUpdated) {
		var ret int64
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetLastUpdatedOk() (*int64, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given int64 and assigns it to the LastUpdated field.
func (o *GetNavigatorResponse) SetLastUpdated(v int64) {
	o.LastUpdated = &v
}

// GetLastUpdatedBy returns the LastUpdatedBy field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetLastUpdatedBy() string {
	if o == nil || IsNil(o.LastUpdatedBy) {
		var ret string
		return ret
	}
	return *o.LastUpdatedBy
}

// GetLastUpdatedByOk returns a tuple with the LastUpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetLastUpdatedByOk() (*string, bool) {
	if o == nil || IsNil(o.LastUpdatedBy) {
		return nil, false
	}
	return o.LastUpdatedBy, true
}

// HasLastUpdatedBy returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasLastUpdatedBy() bool {
	if o != nil && !IsNil(o.LastUpdatedBy) {
		return true
	}

	return false
}

// SetLastUpdatedBy gets a reference to the given string and assigns it to the LastUpdatedBy field.
func (o *GetNavigatorResponse) SetLastUpdatedBy(v string) {
	o.LastUpdatedBy = &v
}

// GetListColumns returns the ListColumns field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetListColumns() []ListColumn {
	if o == nil || IsNil(o.ListColumns) {
		var ret []ListColumn
		return ret
	}
	return o.ListColumns
}

// GetListColumnsOk returns a tuple with the ListColumns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetListColumnsOk() ([]ListColumn, bool) {
	if o == nil || IsNil(o.ListColumns) {
		return nil, false
	}
	return o.ListColumns, true
}

// HasListColumns returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasListColumns() bool {
	if o != nil && !IsNil(o.ListColumns) {
		return true
	}

	return false
}

// SetListColumns gets a reference to the given []ListColumn and assigns it to the ListColumns field.
func (o *GetNavigatorResponse) SetListColumns(v []ListColumn) {
	o.ListColumns = v
}

// GetNavigatorCode returns the NavigatorCode field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetNavigatorCode() string {
	if o == nil || IsNil(o.NavigatorCode) {
		var ret string
		return ret
	}
	return *o.NavigatorCode
}

// GetNavigatorCodeOk returns a tuple with the NavigatorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetNavigatorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.NavigatorCode) {
		return nil, false
	}
	return o.NavigatorCode, true
}

// HasNavigatorCode returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasNavigatorCode() bool {
	if o != nil && !IsNil(o.NavigatorCode) {
		return true
	}

	return false
}

// SetNavigatorCode gets a reference to the given string and assigns it to the NavigatorCode field.
func (o *GetNavigatorResponse) SetNavigatorCode(v string) {
	o.NavigatorCode = &v
}

// GetOwnerScope returns the OwnerScope field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetOwnerScope() OwnerScope {
	if o == nil || IsNil(o.OwnerScope) {
		var ret OwnerScope
		return ret
	}
	return *o.OwnerScope
}

// GetOwnerScopeOk returns a tuple with the OwnerScope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetOwnerScopeOk() (*OwnerScope, bool) {
	if o == nil || IsNil(o.OwnerScope) {
		return nil, false
	}
	return o.OwnerScope, true
}

// HasOwnerScope returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasOwnerScope() bool {
	if o != nil && !IsNil(o.OwnerScope) {
		return true
	}

	return false
}

// SetOwnerScope gets a reference to the given OwnerScope and assigns it to the OwnerScope field.
func (o *GetNavigatorResponse) SetOwnerScope(v OwnerScope) {
	o.OwnerScope = &v
}

// GetPropertyIdentifierTemplate returns the PropertyIdentifierTemplate field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetPropertyIdentifierTemplate() string {
	if o == nil || IsNil(o.PropertyIdentifierTemplate) {
		var ret string
		return ret
	}
	return *o.PropertyIdentifierTemplate
}

// GetPropertyIdentifierTemplateOk returns a tuple with the PropertyIdentifierTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetPropertyIdentifierTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.PropertyIdentifierTemplate) {
		return nil, false
	}
	return o.PropertyIdentifierTemplate, true
}

// HasPropertyIdentifierTemplate returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasPropertyIdentifierTemplate() bool {
	if o != nil && !IsNil(o.PropertyIdentifierTemplate) {
		return true
	}

	return false
}

// SetPropertyIdentifierTemplate gets a reference to the given string and assigns it to the PropertyIdentifierTemplate field.
func (o *GetNavigatorResponse) SetPropertyIdentifierTemplate(v string) {
	o.PropertyIdentifierTemplate = &v
}

// GetEntityMetrics returns the EntityMetrics field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetEntityMetrics() []Metric {
	if o == nil || IsNil(o.EntityMetrics) {
		var ret []Metric
		return ret
	}
	return o.EntityMetrics
}

// GetEntityMetricsOk returns a tuple with the EntityMetrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetEntityMetricsOk() ([]Metric, bool) {
	if o == nil || IsNil(o.EntityMetrics) {
		return nil, false
	}
	return o.EntityMetrics, true
}

// HasEntityMetrics returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasEntityMetrics() bool {
	if o != nil && !IsNil(o.EntityMetrics) {
		return true
	}

	return false
}

// SetEntityMetrics gets a reference to the given []Metric and assigns it to the EntityMetrics field.
func (o *GetNavigatorResponse) SetEntityMetrics(v []Metric) {
	o.EntityMetrics = v
}

// GetSystemTypes returns the SystemTypes field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetSystemTypes() []string {
	if o == nil || IsNil(o.SystemTypes) {
		var ret []string
		return ret
	}
	return o.SystemTypes
}

// GetSystemTypesOk returns a tuple with the SystemTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetSystemTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.SystemTypes) {
		return nil, false
	}
	return o.SystemTypes, true
}

// HasSystemTypes returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasSystemTypes() bool {
	if o != nil && !IsNil(o.SystemTypes) {
		return true
	}

	return false
}

// SetSystemTypes gets a reference to the given []string and assigns it to the SystemTypes field.
func (o *GetNavigatorResponse) SetSystemTypes(v []string) {
	o.SystemTypes = v
}

// GetSummaryMetricLabel returns the SummaryMetricLabel field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetSummaryMetricLabel() string {
	if o == nil || IsNil(o.SummaryMetricLabel) {
		var ret string
		return ret
	}
	return *o.SummaryMetricLabel
}

// GetSummaryMetricLabelOk returns a tuple with the SummaryMetricLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetSummaryMetricLabelOk() (*string, bool) {
	if o == nil || IsNil(o.SummaryMetricLabel) {
		return nil, false
	}
	return o.SummaryMetricLabel, true
}

// HasSummaryMetricLabel returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasSummaryMetricLabel() bool {
	if o != nil && !IsNil(o.SummaryMetricLabel) {
		return true
	}

	return false
}

// SetSummaryMetricLabel gets a reference to the given string and assigns it to the SummaryMetricLabel field.
func (o *GetNavigatorResponse) SetSummaryMetricLabel(v string) {
	o.SummaryMetricLabel = &v
}

// GetSummaryMetricProgramText returns the SummaryMetricProgramText field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetSummaryMetricProgramText() string {
	if o == nil || IsNil(o.SummaryMetricProgramText) {
		var ret string
		return ret
	}
	return *o.SummaryMetricProgramText
}

// GetSummaryMetricProgramTextOk returns a tuple with the SummaryMetricProgramText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetSummaryMetricProgramTextOk() (*string, bool) {
	if o == nil || IsNil(o.SummaryMetricProgramText) {
		return nil, false
	}
	return o.SummaryMetricProgramText, true
}

// HasSummaryMetricProgramText returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasSummaryMetricProgramText() bool {
	if o != nil && !IsNil(o.SummaryMetricProgramText) {
		return true
	}

	return false
}

// SetSummaryMetricProgramText gets a reference to the given string and assigns it to the SummaryMetricProgramText field.
func (o *GetNavigatorResponse) SetSummaryMetricProgramText(v string) {
	o.SummaryMetricProgramText = &v
}

// GetTooltipKeyList returns the TooltipKeyList field value if set, zero value otherwise.
func (o *GetNavigatorResponse) GetTooltipKeyList() []TooltipKey {
	if o == nil || IsNil(o.TooltipKeyList) {
		var ret []TooltipKey
		return ret
	}
	return o.TooltipKeyList
}

// GetTooltipKeyListOk returns a tuple with the TooltipKeyList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNavigatorResponse) GetTooltipKeyListOk() ([]TooltipKey, bool) {
	if o == nil || IsNil(o.TooltipKeyList) {
		return nil, false
	}
	return o.TooltipKeyList, true
}

// HasTooltipKeyList returns a boolean if a field has been set.
func (o *GetNavigatorResponse) HasTooltipKeyList() bool {
	if o != nil && !IsNil(o.TooltipKeyList) {
		return true
	}

	return false
}

// SetTooltipKeyList gets a reference to the given []TooltipKey and assigns it to the TooltipKeyList field.
func (o *GetNavigatorResponse) SetTooltipKeyList(v []TooltipKey) {
	o.TooltipKeyList = v
}

func (o GetNavigatorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNavigatorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AggregateDashboards) {
		toSerialize["aggregateDashboards"] = o.AggregateDashboards
	}
	if !IsNil(o.AlertQuery) {
		toSerialize["alertQuery"] = o.AlertQuery
	}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Creator) {
		toSerialize["creator"] = o.Creator
	}
	if !IsNil(o.DefaultGroupBy) {
		toSerialize["defaultGroupBy"] = o.DefaultGroupBy
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IdDisplayName) {
		toSerialize["idDisplayName"] = o.IdDisplayName
	}
	if !IsNil(o.InstanceDashboards) {
		toSerialize["instanceDashboards"] = o.InstanceDashboards
	}
	if !IsNil(o.InstanceDisplayText) {
		toSerialize["instanceDisplayText"] = o.InstanceDisplayText
	}
	if !IsNil(o.InstanceLabel) {
		toSerialize["instanceLabel"] = o.InstanceLabel
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["lastUpdated"] = o.LastUpdated
	}
	if !IsNil(o.LastUpdatedBy) {
		toSerialize["lastUpdatedBy"] = o.LastUpdatedBy
	}
	if !IsNil(o.ListColumns) {
		toSerialize["listColumns"] = o.ListColumns
	}
	if !IsNil(o.NavigatorCode) {
		toSerialize["navigatorCode"] = o.NavigatorCode
	}
	if !IsNil(o.OwnerScope) {
		toSerialize["ownerScope"] = o.OwnerScope
	}
	if !IsNil(o.PropertyIdentifierTemplate) {
		toSerialize["propertyIdentifierTemplate"] = o.PropertyIdentifierTemplate
	}
	if !IsNil(o.EntityMetrics) {
		toSerialize["entityMetrics"] = o.EntityMetrics
	}
	if !IsNil(o.SystemTypes) {
		toSerialize["systemTypes"] = o.SystemTypes
	}
	if !IsNil(o.SummaryMetricLabel) {
		toSerialize["summaryMetricLabel"] = o.SummaryMetricLabel
	}
	if !IsNil(o.SummaryMetricProgramText) {
		toSerialize["summaryMetricProgramText"] = o.SummaryMetricProgramText
	}
	if !IsNil(o.TooltipKeyList) {
		toSerialize["tooltipKeyList"] = o.TooltipKeyList
	}
	return toSerialize, nil
}

type NullableGetNavigatorResponse struct {
	value *GetNavigatorResponse
	isSet bool
}

func (v NullableGetNavigatorResponse) Get() *GetNavigatorResponse {
	return v.value
}

func (v *NullableGetNavigatorResponse) Set(val *GetNavigatorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNavigatorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNavigatorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNavigatorResponse(val *GetNavigatorResponse) *NullableGetNavigatorResponse {
	return &NullableGetNavigatorResponse{value: val, isSet: true}
}

func (v NullableGetNavigatorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNavigatorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


