/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
)

// checks if the CreateNavigatorCustomizationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNavigatorCustomizationRequest{}

// CreateNavigatorCustomizationRequest struct for CreateNavigatorCustomizationRequest
type CreateNavigatorCustomizationRequest struct {
	// Navigator customization system ID 
	Id *string `json:"id,omitempty"`
	// Navigator customization display name 
	Name *string `json:"name,omitempty"`
	// Navigator system ID 
	NavigatorId *string `json:"navigatorId,omitempty"`
	// Array of dashboard IDs to use for aggregate display. Specific to GET /navigator/{id}/navigatorcustomization. 
	AggregateDashboards []string `json:"aggregateDashboards,omitempty"`
	// Array of dashboard IDs to use for instance display. Specific to GET /navigator/{id}/navigatorcustomization. 
	InstanceDashboards []string `json:"instanceDashboards,omitempty"`
	// Navigator customization creation time 
	Created *int64 `json:"created,omitempty"`
	// User ID of the user who created this navigator customization 
	Creator *string `json:"creator,omitempty"`
	// Time at which the navigator customization was last updated 
	LastUpdated *int64 `json:"lastUpdated,omitempty"`
	// ID of the user who last updated this navigator customization 
	LastUpdatedBy *string `json:"lastUpdatedBy,omitempty"`
}

// NewCreateNavigatorCustomizationRequest instantiates a new CreateNavigatorCustomizationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNavigatorCustomizationRequest() *CreateNavigatorCustomizationRequest {
	this := CreateNavigatorCustomizationRequest{}
	return &this
}

// NewCreateNavigatorCustomizationRequestWithDefaults instantiates a new CreateNavigatorCustomizationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNavigatorCustomizationRequestWithDefaults() *CreateNavigatorCustomizationRequest {
	this := CreateNavigatorCustomizationRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateNavigatorCustomizationRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNavigatorCustomizationRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateNavigatorCustomizationRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateNavigatorCustomizationRequest) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateNavigatorCustomizationRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNavigatorCustomizationRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateNavigatorCustomizationRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateNavigatorCustomizationRequest) SetName(v string) {
	o.Name = &v
}

// GetNavigatorId returns the NavigatorId field value if set, zero value otherwise.
func (o *CreateNavigatorCustomizationRequest) GetNavigatorId() string {
	if o == nil || IsNil(o.NavigatorId) {
		var ret string
		return ret
	}
	return *o.NavigatorId
}

// GetNavigatorIdOk returns a tuple with the NavigatorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNavigatorCustomizationRequest) GetNavigatorIdOk() (*string, bool) {
	if o == nil || IsNil(o.NavigatorId) {
		return nil, false
	}
	return o.NavigatorId, true
}

// HasNavigatorId returns a boolean if a field has been set.
func (o *CreateNavigatorCustomizationRequest) HasNavigatorId() bool {
	if o != nil && !IsNil(o.NavigatorId) {
		return true
	}

	return false
}

// SetNavigatorId gets a reference to the given string and assigns it to the NavigatorId field.
func (o *CreateNavigatorCustomizationRequest) SetNavigatorId(v string) {
	o.NavigatorId = &v
}

// GetAggregateDashboards returns the AggregateDashboards field value if set, zero value otherwise.
func (o *CreateNavigatorCustomizationRequest) GetAggregateDashboards() []string {
	if o == nil || IsNil(o.AggregateDashboards) {
		var ret []string
		return ret
	}
	return o.AggregateDashboards
}

// GetAggregateDashboardsOk returns a tuple with the AggregateDashboards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNavigatorCustomizationRequest) GetAggregateDashboardsOk() ([]string, bool) {
	if o == nil || IsNil(o.AggregateDashboards) {
		return nil, false
	}
	return o.AggregateDashboards, true
}

// HasAggregateDashboards returns a boolean if a field has been set.
func (o *CreateNavigatorCustomizationRequest) HasAggregateDashboards() bool {
	if o != nil && !IsNil(o.AggregateDashboards) {
		return true
	}

	return false
}

// SetAggregateDashboards gets a reference to the given []string and assigns it to the AggregateDashboards field.
func (o *CreateNavigatorCustomizationRequest) SetAggregateDashboards(v []string) {
	o.AggregateDashboards = v
}

// GetInstanceDashboards returns the InstanceDashboards field value if set, zero value otherwise.
func (o *CreateNavigatorCustomizationRequest) GetInstanceDashboards() []string {
	if o == nil || IsNil(o.InstanceDashboards) {
		var ret []string
		return ret
	}
	return o.InstanceDashboards
}

// GetInstanceDashboardsOk returns a tuple with the InstanceDashboards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNavigatorCustomizationRequest) GetInstanceDashboardsOk() ([]string, bool) {
	if o == nil || IsNil(o.InstanceDashboards) {
		return nil, false
	}
	return o.InstanceDashboards, true
}

// HasInstanceDashboards returns a boolean if a field has been set.
func (o *CreateNavigatorCustomizationRequest) HasInstanceDashboards() bool {
	if o != nil && !IsNil(o.InstanceDashboards) {
		return true
	}

	return false
}

// SetInstanceDashboards gets a reference to the given []string and assigns it to the InstanceDashboards field.
func (o *CreateNavigatorCustomizationRequest) SetInstanceDashboards(v []string) {
	o.InstanceDashboards = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *CreateNavigatorCustomizationRequest) GetCreated() int64 {
	if o == nil || IsNil(o.Created) {
		var ret int64
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNavigatorCustomizationRequest) GetCreatedOk() (*int64, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *CreateNavigatorCustomizationRequest) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given int64 and assigns it to the Created field.
func (o *CreateNavigatorCustomizationRequest) SetCreated(v int64) {
	o.Created = &v
}

// GetCreator returns the Creator field value if set, zero value otherwise.
func (o *CreateNavigatorCustomizationRequest) GetCreator() string {
	if o == nil || IsNil(o.Creator) {
		var ret string
		return ret
	}
	return *o.Creator
}

// GetCreatorOk returns a tuple with the Creator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNavigatorCustomizationRequest) GetCreatorOk() (*string, bool) {
	if o == nil || IsNil(o.Creator) {
		return nil, false
	}
	return o.Creator, true
}

// HasCreator returns a boolean if a field has been set.
func (o *CreateNavigatorCustomizationRequest) HasCreator() bool {
	if o != nil && !IsNil(o.Creator) {
		return true
	}

	return false
}

// SetCreator gets a reference to the given string and assigns it to the Creator field.
func (o *CreateNavigatorCustomizationRequest) SetCreator(v string) {
	o.Creator = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *CreateNavigatorCustomizationRequest) GetLastUpdated() int64 {
	if o == nil || IsNil(o.LastUpdated) {
		var ret int64
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNavigatorCustomizationRequest) GetLastUpdatedOk() (*int64, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *CreateNavigatorCustomizationRequest) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given int64 and assigns it to the LastUpdated field.
func (o *CreateNavigatorCustomizationRequest) SetLastUpdated(v int64) {
	o.LastUpdated = &v
}

// GetLastUpdatedBy returns the LastUpdatedBy field value if set, zero value otherwise.
func (o *CreateNavigatorCustomizationRequest) GetLastUpdatedBy() string {
	if o == nil || IsNil(o.LastUpdatedBy) {
		var ret string
		return ret
	}
	return *o.LastUpdatedBy
}

// GetLastUpdatedByOk returns a tuple with the LastUpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNavigatorCustomizationRequest) GetLastUpdatedByOk() (*string, bool) {
	if o == nil || IsNil(o.LastUpdatedBy) {
		return nil, false
	}
	return o.LastUpdatedBy, true
}

// HasLastUpdatedBy returns a boolean if a field has been set.
func (o *CreateNavigatorCustomizationRequest) HasLastUpdatedBy() bool {
	if o != nil && !IsNil(o.LastUpdatedBy) {
		return true
	}

	return false
}

// SetLastUpdatedBy gets a reference to the given string and assigns it to the LastUpdatedBy field.
func (o *CreateNavigatorCustomizationRequest) SetLastUpdatedBy(v string) {
	o.LastUpdatedBy = &v
}

func (o CreateNavigatorCustomizationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNavigatorCustomizationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NavigatorId) {
		toSerialize["navigatorId"] = o.NavigatorId
	}
	if !IsNil(o.AggregateDashboards) {
		toSerialize["aggregateDashboards"] = o.AggregateDashboards
	}
	if !IsNil(o.InstanceDashboards) {
		toSerialize["instanceDashboards"] = o.InstanceDashboards
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Creator) {
		toSerialize["creator"] = o.Creator
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["lastUpdated"] = o.LastUpdated
	}
	if !IsNil(o.LastUpdatedBy) {
		toSerialize["lastUpdatedBy"] = o.LastUpdatedBy
	}
	return toSerialize, nil
}

type NullableCreateNavigatorCustomizationRequest struct {
	value *CreateNavigatorCustomizationRequest
	isSet bool
}

func (v NullableCreateNavigatorCustomizationRequest) Get() *CreateNavigatorCustomizationRequest {
	return v.value
}

func (v *NullableCreateNavigatorCustomizationRequest) Set(val *CreateNavigatorCustomizationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNavigatorCustomizationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNavigatorCustomizationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNavigatorCustomizationRequest(val *CreateNavigatorCustomizationRequest) *NullableCreateNavigatorCustomizationRequest {
	return &NullableCreateNavigatorCustomizationRequest{value: val, isSet: true}
}

func (v NullableCreateNavigatorCustomizationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNavigatorCustomizationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


