/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListColumn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListColumn{}

// ListColumn List column item 
type ListColumn struct {
	// Column display name 
	DisplayName string `json:"displayName"`
	// Column format 
	Format *string `json:"format,omitempty"`
	// Custom property or dimension 
	Property string `json:"property"`
}

type _ListColumn ListColumn

// NewListColumn instantiates a new ListColumn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListColumn(displayName string, property string) *ListColumn {
	this := ListColumn{}
	this.DisplayName = displayName
	this.Property = property
	return &this
}

// NewListColumnWithDefaults instantiates a new ListColumn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListColumnWithDefaults() *ListColumn {
	this := ListColumn{}
	return &this
}

// GetDisplayName returns the DisplayName field value
func (o *ListColumn) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ListColumn) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ListColumn) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *ListColumn) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListColumn) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *ListColumn) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *ListColumn) SetFormat(v string) {
	o.Format = &v
}

// GetProperty returns the Property field value
func (o *ListColumn) GetProperty() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Property
}

// GetPropertyOk returns a tuple with the Property field value
// and a boolean to check if the value has been set.
func (o *ListColumn) GetPropertyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Property, true
}

// SetProperty sets field value
func (o *ListColumn) SetProperty(v string) {
	o.Property = v
}

func (o ListColumn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListColumn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["displayName"] = o.DisplayName
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	toSerialize["property"] = o.Property
	return toSerialize, nil
}

func (o *ListColumn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"displayName",
		"property",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListColumn := _ListColumn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListColumn)

	if err != nil {
		return err
	}

	*o = ListColumn(varListColumn)

	return err
}

type NullableListColumn struct {
	value *ListColumn
	isSet bool
}

func (v NullableListColumn) Get() *ListColumn {
	return v.value
}

func (v *NullableListColumn) Set(val *ListColumn) {
	v.value = val
	v.isSet = true
}

func (v NullableListColumn) IsSet() bool {
	return v.isSet
}

func (v *NullableListColumn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListColumn(val *ListColumn) *NullableListColumn {
	return &NullableListColumn{value: val, isSet: true}
}

func (v NullableListColumn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListColumn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


