/*
Navigators API

API for creating, updating, retrieving, and deleting custom navigators.  ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin role to use the `POST /navigator`, `PUT /navigator/{id}`, `DELETE /navigator/{id}`, `POST /navigator/{id}/navigatorcustomization`, `PUT /navigator/{id}/navigatorcustomization/{customizationId}`, and `DELETE /navigator/{id}/navigatorcustomization/{customizationId}` operations. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the `GET /navigator`, `GET /navigator/{id}`, `GET /navigator/{id}/dashboards`, `GET /navigator/{id}/navigatorcustomization`, and `GET /navigator/{id}/navigatorcustomization/{customizationId}` operations. 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package navigator

import (
	"encoding/json"
	"fmt"
)

// OwnerScope Indicates how this navigator was created. 
type OwnerScope string

// List of OwnerScope
const (
	SPLUNK OwnerScope = "splunk"
	ORGANIZATION OwnerScope = "organization"
)

// All allowed values of OwnerScope enum
var AllowedOwnerScopeEnumValues = []OwnerScope{
	"splunk",
	"organization",
}

func (v *OwnerScope) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OwnerScope(value)
	for _, existing := range AllowedOwnerScopeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OwnerScope", value)
}

// NewOwnerScopeFromValue returns a pointer to a valid OwnerScope
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOwnerScopeFromValue(v string) (*OwnerScope, error) {
	ev := OwnerScope(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OwnerScope: valid values are %v", v, AllowedOwnerScopeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OwnerScope) IsValid() bool {
	for _, existing := range AllowedOwnerScopeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OwnerScope value
func (v OwnerScope) Ptr() *OwnerScope {
	return &v
}

type NullableOwnerScope struct {
	value *OwnerScope
	isSet bool
}

func (v NullableOwnerScope) Get() *OwnerScope {
	return v.value
}

func (v *NullableOwnerScope) Set(val *OwnerScope) {
	v.value = val
	v.isSet = true
}

func (v NullableOwnerScope) IsSet() bool {
	return v.isSet
}

func (v *NullableOwnerScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOwnerScope(val *OwnerScope) *NullableOwnerScope {
	return &NullableOwnerScope{value: val, isSet: true}
}

func (v NullableOwnerScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOwnerScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

