/*
Metric Ingest Ruleset API

Metric ingest ruleset API

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metric_ruleset

import (
	"encoding/json"
	"fmt"
)

// Destination The routing destination for your data points 
type Destination string

// List of Destination
const (
	UNKNOWN Destination = "Unknown"
	REALTIME_13_MO Destination = "Realtime_13MO"
	REALTIME_3_MO Destination = "Realtime_3MO"
	HCM Destination = "HCM"
	FULL_FIDELITY Destination = "FullFidelity"
	DROP Destination = "Drop"
)

// All allowed values of Destination enum
var AllowedDestinationEnumValues = []Destination{
	"Unknown",
	"Realtime_13MO",
	"Realtime_3MO",
	"HCM",
	"FullFidelity",
	"Drop",
}

func (v *Destination) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Destination(value)
	for _, existing := range AllowedDestinationEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Destination", value)
}