/*
Metric Ingest Ruleset API

Metric ingest ruleset API

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metric_ruleset

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// MetricMatcher - Metric matcher for the ruleset
type MetricMatcher struct {
	SimpleMetricMatcher *SimpleMetricMatcher
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *MetricMatcher) UnmarshalJSON(data []byte) error {
	var err error

	// try to unmarshal data into SimpleMetricMatcher
	err = json.NewDecoder(bytes.NewBuffer(data)).Decode(&dst.SimpleMetricMatcher)
	if err != nil {
		return err
	}

	jsonSimpleMetricMatcher, _ := json.Marshal(dst.SimpleMetricMatcher)
	if string(jsonSimpleMetricMatcher) == "{}" { // empty struct
		dst.SimpleMetricMatcher = nil
		fmt.Errorf("Data failed to match schemas in oneOf(MetricMatcher)")
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src MetricMatcher) MarshalJSON() ([]byte, error) {
	if src.SimpleMetricMatcher != nil {
		return json.Marshal(&src.SimpleMetricMatcher)
	}

	return nil, nil // no data in oneOf schemas
}
