/*
Metric Ingest Ruleset API

Metric ingest ruleset API

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metric_ruleset

import (
	"encoding/json"
)

// SimpleMetricMatcher Create a simple metric matcher
type SimpleMetricMatcher struct {
	// Metric matcher type
	Type string `json:"type"`
	// Metric name you want to match
	MetricName string `json:"metricName"`
	// Filtering rules you want to apply to your selected metrics
	Filters []PropertyFilter `json:"filters,omitempty"`
}

func (o SimpleMetricMatcher) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["metricName"] = o.MetricName
	}
	if o.Filters != nil {
		toSerialize["filters"] = o.Filters
	}
	return json.Marshal(toSerialize)
}
