/*
Metric Ruleset API

Metric ruleset API 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metric_ruleset

import (
	"encoding/json"
)

// AggregationRule A single aggregation rule in a metric ruleset 
type AggregationRule struct {
	Matcher MetricMatcher `json:"matcher"`
	// Status of this aggregation rule 
	Enabled bool `json:"enabled"`
	Aggregator MetricAggregator `json:"aggregator"`
}

// NewAggregationRule instantiates a new AggregationRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregationRule(matcher MetricMatcher, enabled bool, aggregator MetricAggregator) *AggregationRule {
	this := AggregationRule{}
	this.Matcher = matcher
	this.Enabled = enabled
	this.Aggregator = aggregator
	return &this
}

// NewAggregationRuleWithDefaults instantiates a new AggregationRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregationRuleWithDefaults() *AggregationRule {
	this := AggregationRule{}
	var enabled bool = false
	this.Enabled = enabled
	return &this
}

// GetMatcher returns the Matcher field value
func (o *AggregationRule) GetMatcher() MetricMatcher {
	if o == nil {
		var ret MetricMatcher
		return ret
	}

	return o.Matcher
}

// GetMatcherOk returns a tuple with the Matcher field value
// and a boolean to check if the value has been set.
func (o *AggregationRule) GetMatcherOk() (*MetricMatcher, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Matcher, true
}

// SetMatcher sets field value
func (o *AggregationRule) SetMatcher(v MetricMatcher) {
	o.Matcher = v
}

// GetEnabled returns the Enabled field value
func (o *AggregationRule) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *AggregationRule) GetEnabledOk() (*bool, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *AggregationRule) SetEnabled(v bool) {
	o.Enabled = v
}

// GetAggregator returns the Aggregator field value
func (o *AggregationRule) GetAggregator() MetricAggregator {
	if o == nil {
		var ret MetricAggregator
		return ret
	}

	return o.Aggregator
}

// GetAggregatorOk returns a tuple with the Aggregator field value
// and a boolean to check if the value has been set.
func (o *AggregationRule) GetAggregatorOk() (*MetricAggregator, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Aggregator, true
}

// SetAggregator sets field value
func (o *AggregationRule) SetAggregator(v MetricAggregator) {
	o.Aggregator = v
}

func (o AggregationRule) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["matcher"] = o.Matcher
	}
	if true {
		toSerialize["enabled"] = o.Enabled
	}
	if true {
		toSerialize["aggregator"] = o.Aggregator
	}
	return json.Marshal(toSerialize)
}

type NullableAggregationRule struct {
	value *AggregationRule
	isSet bool
}

func (v NullableAggregationRule) Get() *AggregationRule {
	return v.value
}

func (v *NullableAggregationRule) Set(val *AggregationRule) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregationRule) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregationRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregationRule(val *AggregationRule) *NullableAggregationRule {
	return &NullableAggregationRule{value: val, isSet: true}
}

func (v NullableAggregationRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregationRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


