/*
Metric Ruleset API

Metric ruleset API 

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metric_ruleset

import (
	"encoding/json"
)

// GenerateAggregationNameRequest Request body for Generate Aggregated Metric Name 
type GenerateAggregationNameRequest struct {
	// Name of the metric 
	MetricName string `json:"metricName"`
	// Dimensions you want to keep in the aggregation rule 
	Dimensions []string `json:"dimensions"`
	// Flag toggling if the dimensions are being dropped 
	DropDimensions *bool `json:"dropDimensions,omitempty"`
}

// NewGenerateAggregationNameRequest instantiates a new GenerateAggregationNameRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateAggregationNameRequest(metricName string, dimensions []string) *GenerateAggregationNameRequest {
	this := GenerateAggregationNameRequest{}
	this.MetricName = metricName
	this.Dimensions = dimensions
	return &this
}

// NewGenerateAggregationNameRequestWithDefaults instantiates a new GenerateAggregationNameRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateAggregationNameRequestWithDefaults() *GenerateAggregationNameRequest {
	this := GenerateAggregationNameRequest{}
	return &this
}

// GetMetricName returns the MetricName field value
func (o *GenerateAggregationNameRequest) GetMetricName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MetricName
}

// GetMetricNameOk returns a tuple with the MetricName field value
// and a boolean to check if the value has been set.
func (o *GenerateAggregationNameRequest) GetMetricNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.MetricName, true
}

// SetMetricName sets field value
func (o *GenerateAggregationNameRequest) SetMetricName(v string) {
	o.MetricName = v
}

// GetDimensions returns the Dimensions field value
func (o *GenerateAggregationNameRequest) GetDimensions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Dimensions
}

// GetDimensionsOk returns a tuple with the Dimensions field value
// and a boolean to check if the value has been set.
func (o *GenerateAggregationNameRequest) GetDimensionsOk() ([]string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Dimensions, true
}

// SetDimensions sets field value
func (o *GenerateAggregationNameRequest) SetDimensions(v []string) {
	o.Dimensions = v
}

// GetDropDimensions returns the DropDimensions field value if set, zero value otherwise.
func (o *GenerateAggregationNameRequest) GetDropDimensions() bool {
	if o == nil || isNil(o.DropDimensions) {
		var ret bool
		return ret
	}
	return *o.DropDimensions
}

// GetDropDimensionsOk returns a tuple with the DropDimensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateAggregationNameRequest) GetDropDimensionsOk() (*bool, bool) {
	if o == nil || isNil(o.DropDimensions) {
    return nil, false
	}
	return o.DropDimensions, true
}

// HasDropDimensions returns a boolean if a field has been set.
func (o *GenerateAggregationNameRequest) HasDropDimensions() bool {
	if o != nil && !isNil(o.DropDimensions) {
		return true
	}

	return false
}

// SetDropDimensions gets a reference to the given bool and assigns it to the DropDimensions field.
func (o *GenerateAggregationNameRequest) SetDropDimensions(v bool) {
	o.DropDimensions = &v
}

func (o GenerateAggregationNameRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["metricName"] = o.MetricName
	}
	if true {
		toSerialize["dimensions"] = o.Dimensions
	}
	if !isNil(o.DropDimensions) {
		toSerialize["dropDimensions"] = o.DropDimensions
	}
	return json.Marshal(toSerialize)
}

type NullableGenerateAggregationNameRequest struct {
	value *GenerateAggregationNameRequest
	isSet bool
}

func (v NullableGenerateAggregationNameRequest) Get() *GenerateAggregationNameRequest {
	return v.value
}

func (v *NullableGenerateAggregationNameRequest) Set(val *GenerateAggregationNameRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateAggregationNameRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateAggregationNameRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateAggregationNameRequest(val *GenerateAggregationNameRequest) *NullableGenerateAggregationNameRequest {
	return &NullableGenerateAggregationNameRequest{value: val, isSet: true}
}

func (v NullableGenerateAggregationNameRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateAggregationNameRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


