version: 2.1
jobs:
  test:
    parameters:
      go_version:
        type: string
      # Needed to paper over differences between Go with and without modules
      dir:
        type: string
        default: ~/project
    working_directory: "<< parameters.dir >>"
    docker:
      - image: "golang:<< parameters.go_version >>"
    steps:
      - checkout
      - run: |
          go mod download

          # Used for code generation
          go get github.com/mauricelam/genny
          go get golang.org/x/tools/cmd/goimports

          go generate ./...
          go test ./... -parallel 4
workflows:
  version: 2
  build:
    jobs:
      - test:
          name: "Go 1.11"
          go_version: "1.11"
      - test:
          name: "Go 1.12"
          go_version: "1.12"
      - test:
          name: "Go 1.13"
          go_version: "1.13"
