/*
Automated Archival API

APIs to manipulate automated archival settings and exempt metrics

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package automated_archival

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExemptMetricDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExemptMetricDeleteRequest{}

// ExemptMetricDeleteRequest struct for ExemptMetricDeleteRequest
type ExemptMetricDeleteRequest struct {
	Ids []string `json:"ids"`
}

type _ExemptMetricDeleteRequest ExemptMetricDeleteRequest

// NewExemptMetricDeleteRequest instantiates a new ExemptMetricDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExemptMetricDeleteRequest(ids []string) *ExemptMetricDeleteRequest {
	this := ExemptMetricDeleteRequest{}
	this.Ids = ids
	return &this
}

// NewExemptMetricDeleteRequestWithDefaults instantiates a new ExemptMetricDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExemptMetricDeleteRequestWithDefaults() *ExemptMetricDeleteRequest {
	this := ExemptMetricDeleteRequest{}
	return &this
}

// GetIds returns the Ids field value
func (o *ExemptMetricDeleteRequest) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *ExemptMetricDeleteRequest) GetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *ExemptMetricDeleteRequest) SetIds(v []string) {
	o.Ids = v
}

func (o ExemptMetricDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExemptMetricDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ids"] = o.Ids
	return toSerialize, nil
}

func (o *ExemptMetricDeleteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExemptMetricDeleteRequest := _ExemptMetricDeleteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExemptMetricDeleteRequest)

	if err != nil {
		return err
	}

	*o = ExemptMetricDeleteRequest(varExemptMetricDeleteRequest)

	return err
}

type NullableExemptMetricDeleteRequest struct {
	value *ExemptMetricDeleteRequest
	isSet bool
}

func (v NullableExemptMetricDeleteRequest) Get() *ExemptMetricDeleteRequest {
	return v.value
}

func (v *NullableExemptMetricDeleteRequest) Set(val *ExemptMetricDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExemptMetricDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExemptMetricDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExemptMetricDeleteRequest(val *ExemptMetricDeleteRequest) *NullableExemptMetricDeleteRequest {
	return &NullableExemptMetricDeleteRequest{value: val, isSet: true}
}

func (v NullableExemptMetricDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExemptMetricDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


