/*
APM service topology API

APIs to retrieve the upstream and downstream dependencies for a given service, as well as to retrieve the complete graph-based topology of all services in a given environment and time window. You can also use tagFilters to filter this topology by indexed span tags.  To learn about example use cases for this API, see [Retrieve service topology](https://dev.splunk.com/observability/docs/apm/service-topology/) in the developer guide.    ## Requirements  * You must have an organization access token with the API permission or a session token to use the API. * You have to have the Splunk Observability Cloud admin, power, or read_only role to use the APM Service Topology endpoints.

API version: 3.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apm

// RetrieveServiceTopologyResponse struct for RetrieveServiceTopologyResponse
type RetrieveServiceTopologyResponse struct {
	Data *RetrieveServiceTopologyDataResponse `json:"data,omitempty"`
}

type RetrieveServiceTopologyDataResponse struct {
	// List of services that form the nodes of the service topology,  in the form of a JSON array of objects
	Nodes []Node `json:"nodes,omitempty"`
	// List of interactions that occur between services (nodes) in the topology
	Edges []Edge `json:"edges,omitempty"`
}
