name: build-and-test-signalflow
on:
  push:
    branches:
      - main
  pull_request:
    paths:
    - 'signalflow/**'

jobs:
  test-signalflow-package:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        GO_VERSION: [ "1.19", "1.20" ]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.GO_VERSION }}

      - name: Caching dependency
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('signalflow/go.sum') }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          working-directory: signalflow

      - name: Run signalfx-go tests
        run: |
          cd signalflow
          go mod download
          go test -cover -race ./... -parallel 4 -timeout 5m
